In [2]:
import pandas as pd
import json
import re

In [3]:
data_dirty = pd.read_csv("kazan_mosk.csv")
data_dirty

,_Лет_на_сайте,_Ссылка,_Стаж,abbreviatedName,adaptiveReviews,albums,assembledInfoListing,audio,avatar,badges,...,scores,shortName,status,suitabilityHints,topServices,trustBadges,video,wantsBackofficeNoticies,wantsNewOrders,workplaces
0,—,https://profi.ru/profile/KraynovPV2/,—,Павел К.,"{""review"": ""Рекомендую специалиста: ответил мо...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/4f0d7ff886404c179...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 70.64116, ""pmetroWeight"": null}",Павел Крайнов,active,"[{""type"": ""fewReviews"", ""text"": ""Мало отзывов ...","[{""name"": ""установка розетки"", ""spname"": """", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
1,—,https://profi.ru/profile/SabirzanovAS/,—,Альберт С.,"{""review"": ""Рекомендую. Чётко отработал, техза...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/eeacf52cbd614dcbb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 70.35913, ""pmetroWeight"": null}",Альберт Сабирзанов,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
2,—,https://profi.ru/profile/LoginovNA2/,—,Николай Л.,"{""review"": ""Сделал монтаж розеток и кабеля в к...","{""totalCount"": 3, ""edges"": [{""node"": {""id"": ""4...","[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/85c69d877df543609...,"[{""type"": ""hasTeam"", ""text"": ""С командой"", ""de...",...,"{""score"": 70.33303, ""pmetroWeight"": null}",Николай Логинов,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
3,—,https://profi.ru/profile/AlimovAA/,—,Айрат А.,"{""review"": ""Все хорошо"", ""matchedWith"": null}","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/0ca42a160c6a47039...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 70.1631, ""pmetroWeight"": null}",Айрат Алимов,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": false, ""suitableOrders"": true, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
4,—,https://profi.ru/profile/ScherbakovFV/,—,Филипп Щ.,"{""review"": ""благодарим за работу, сделал быстр...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": null, ""__typename...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/36866a6e86464fd08...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.68601, ""pmetroWeight"": null}",Филипп Щербаков,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,—,https://profi.ru/profile/GafiatullinRR/,—,Радик Г.,"{""review"": ""Встретились, отдал ключи, на следу...","{""totalCount"": 6, ""edges"": [{""node"": {""id"": ""1...","[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/d740f52760da4e6cb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.706608, ""pmetroWeight"": null}",Радик Гафиатуллин,active,"[{""type"": ""noReviews"", ""text"": ""Нет отзывов по...","[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
203,—,https://profi.ru/profile/KhristolyubovYA/,—,Евгений Щ.,NaN,"{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": null, ""__typename...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/f3335425f52840bcb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.704235, ""pmetroWeight"": null}",Евгений Щинов,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
204,—,https://profi.ru/profile/ProkhorovNS3/,—,Николай П.,NaN,"{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": null, ""__typename...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/71c5e0ecc5dd48d89...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.69921, ""pmetroWeight"": null}",Николай Прохоров,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
205,—,https://profi.ru/profile/EfimovAS25/,—,Артём Е.,"{""review"": ""Артём с полной ответственностью по...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Опыт более 10...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/38758044e4c442a3b...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.69843, ""pmetroWeight"": null}",Артём Ефимов,active,"[{""type"": ""fewReviews"", ""text"": ""Мало отзывов ...","[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
206,—,https://profi.ru/profile/AnikinVV2/,—,Вячеслав А.,NaN,"{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Работы по&nbs...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/1423b76f62124312b...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.69843, ""pmetroWeight"": null}",Вячеслав Аникин,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]

In [4]:
data_dirty

,_Лет_на_сайте,_Ссылка,_Стаж,abbreviatedName,adaptiveReviews,albums,assembledInfoListing,audio,avatar,badges,...,scores,shortName,status,suitabilityHints,topServices,trustBadges,video,wantsBackofficeNoticies,wantsNewOrders,workplaces
0,—,https://profi.ru/profile/KraynovPV2/,—,Павел К.,"{""review"": ""Рекомендую специалиста: ответил мо...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/4f0d7ff886404c179...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 70.64116, ""pmetroWeight"": null}",Павел Крайнов,active,"[{""type"": ""fewReviews"", ""text"": ""Мало отзывов ...","[{""name"": ""установка розетки"", ""spname"": """", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
1,—,https://profi.ru/profile/SabirzanovAS/,—,Альберт С.,"{""review"": ""Рекомендую. Чётко отработал, техза...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/eeacf52cbd614dcbb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 70.35913, ""pmetroWeight"": null}",Альберт Сабирзанов,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
2,—,https://profi.ru/profile/LoginovNA2/,—,Николай Л.,"{""review"": ""Сделал монтаж розеток и кабеля в к...","{""totalCount"": 3, ""edges"": [{""node"": {""id"": ""4...","[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/85c69d877df543609...,"[{""type"": ""hasTeam"", ""text"": ""С командой"", ""de...",...,"{""score"": 70.33303, ""pmetroWeight"": null}",Николай Логинов,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
3,—,https://profi.ru/profile/AlimovAA/,—,Айрат А.,"{""review"": ""Все хорошо"", ""matchedWith"": null}","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/0ca42a160c6a47039...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 70.1631, ""pmetroWeight"": null}",Айрат Алимов,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": false, ""suitableOrders"": true, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
4,—,https://profi.ru/profile/ScherbakovFV/,—,Филипп Щ.,"{""review"": ""благодарим за работу, сделал быстр...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": null, ""__typename...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/36866a6e86464fd08...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.68601, ""pmetroWeight"": null}",Филипп Щербаков,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,—,https://profi.ru/profile/GafiatullinRR/,—,Радик Г.,"{""review"": ""Встретились, отдал ключи, на следу...","{""totalCount"": 6, ""edges"": [{""node"": {""id"": ""1...","[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/d740f52760da4e6cb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.706608, ""pmetroWeight"": null}",Радик Гафиатуллин,active,"[{""type"": ""noReviews"", ""text"": ""Нет отзывов по...","[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
203,—,https://profi.ru/profile/KhristolyubovYA/,—,Евгений Щ.,NaN,"{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": null, ""__typename...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/f3335425f52840bcb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.704235, ""pmetroWeight"": null}",Евгений Щинов,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
204,—,https://profi.ru/profile/ProkhorovNS3/,—,Николай П.,NaN,"{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": null, ""__typename...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/71c5e0ecc5dd48d89...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.69921, ""pmetroWeight"": null}",Николай Прохоров,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
205,—,https://profi.ru/profile/EfimovAS25/,—,Артём Е.,"{""review"": ""Артём с полной ответственностью по...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Опыт более 10...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/38758044e4c442a3b...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.69843, ""pmetroWeight"": null}",Артём Ефимов,active,"[{""type"": ""fewReviews"", ""text"": ""Мало отзывов ...","[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]
206,—,https://profi.ru/profile/AnikinVV2/,—,Вячеслав А.,NaN,"{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Работы по&nbs...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/1423b76f62124312b...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""score"": 50.69843, ""pmetroWeight"": null}",Вячеслав Аникин,active,[],"[{""name"": ""электрика"", ""spname"": ""электрик"", ""...",[],NaN,"{""general"": true, ""suitableOrders"": false, ""ca...","{""value"": ""YES"", ""status"": null, ""activeDate"":...",[]

In [10]:
def get_json(column_name, index):
            val = data_dirty[column_name][index]
            if isinstance(val, str) and val.strip():
                try:
                    return json.loads(val)
                except:
                    return None
            return None

In [ ]:
def make_dataset(data_dirty):
    rows = []

    for i in range(data_dirty.shape[0]):
        def get_json(column_name, index):
            val = data_dirty[column_name][index]
            if isinstance(val, str) and val.strip():
                try:
                    return json.loads(val)
                except:
                    return None
            return None

        try:
            ## скидка
            discount_data = json.loads(data_dirty['pinfs'][i])['skidka']
            discount = None if not discount_data else discount_data['values'][0]['key']

            ## количество альбомов
            cur_album = json.loads(data_dirty['albums'][i])
            album_count = (cur_album['totalCount'])

            ## количество фоток
            cur_files = json.loads(data_dirty['files'][i])
            photos_count = (cur_files['totalCount'])

            # Проверка паспорта
            badges = get_json('badges', i)
            docs_verified = (badges[0]["type"] == 'verified') if (badges and len(badges) > 0) else False

            # Пол
            gender = data_dirty['gender'][i] if pd.notna(data_dirty['gender'][i]) else None

            # Гарантия
            guarantee_data = get_json('guaranteeBlock', i)
            master_garantee = None
            if guarantee_data and 'content' in guarantee_data and len(guarantee_data['content']) > 1:
                master_garantee = guarantee_data['content'][1].get('template')
            master_garantee = 'Нет гарантии' if not master_garantee else master_garantee
            if master_garantee.split()[0] == 'Советуем':
                master_garantee = 'По договоренности'
            if master_garantee == '«Сделаю скидку»':
                master_garantee = 'По договоренности'

            # Рейтинг и отзывы
            mean_rating = data_dirty['newRank'][i] if pd.notna(data_dirty['newRank'][i]) else 0
            reviews_count = data_dirty['reviewsCount'][i] if pd.notna(data_dirty['reviewsCount'][i]) else 0

            # json с образование и опыт - сложно парсить плюс нет фиксированных категорий - просто закинем в LLM
            experience_education =  data_dirty['assembledInfoListing'][i]

            # Отметка "очень хвалят"
            trust_badges = get_json('trustBadges', i)
            mark_hvalyat = (trust_badges[0]['type'] == 'great') if (trust_badges and len(trust_badges) > 0) else False

            # Проверка квалификации
            cert_data = get_json('certifiedServices', i)
            work_cert = (cert_data.get('title') == 'Квалификация подтверждена') if cert_data else False

            ## id мастера
            master_id = data_dirty.iloc[i, 1]

            # Цена
            ## делаем нормировку на минимальную цену другой похожей категории цены
            price_list = get_json('priceListPreview', i)
            socket_price = None
            if price_list and 'prices' in price_list:
                for item in price_list['prices']:
                    if item.get('price', {}).get('name').lower() == 'установка розеток и выключателей':
                        socket_price = (item['price'].get('from'))
                        norm_coef = 1
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            break

                    if item.get('price', {}).get('name').lower() == 'установка розеток':
                        norm_coef = 1.5
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка розеток')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка розетки':
                        norm_coef = 1
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка розетки')
                            break

                    if item.get('price', {}).get('name').lower() == 'ремонт розеток':
                        norm_coef = 1
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('ремонт розеток')
                            break

                    if item.get('price', {}).get('name').lower() == 'замена розетки':
                        norm_coef = 1.55
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('замена розетки')
                            break

                    if item.get('price', {}).get('name').lower() == 'перенос розетки':
                        norm_coef = 1
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('перенос розетки')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка наружных розеток':
                        norm_coef = 0.9
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка наружных розеток')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка внутренних розеток':
                        norm_coef = 0.9
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка внутренних розеток')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка розетки с заземлением':
                        norm_coef = 0.9
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка розетки с заземлением')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка умной розетки':
                        norm_coef = 1
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка умной розетки')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка уличной розетки':
                        norm_coef = 1
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка уличной розетки')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка розеток в столешницу':
                        norm_coef = 1
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка розеток в столешницу')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка розеток на кухне':
                        norm_coef = 1.5
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка розеток на кухне')
                            break

                    if item.get('price', {}).get('name').lower() == 'установка блока розеток':
                        norm_coef = 1.5
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('установка блока розеток')
                            break

                    if item.get('price', {}).get('name').lower() == 'электрика':
                        norm_coef = 1
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('электрика')
                            break

                    if item.get('price', {}).get('name').lower() == 'aварийный выезд электрика':
                        norm_coef = 3
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price) / norm_coef
                            print('aварийный выезд электрика')
                            break
            ## подсказки от профи ру
            cur_hints = json.loads(data_dirty['suitabilityHints'][i])
            suit_hint = None if not cur_hints else cur_hints[0]['text']

            ## есть ли договор и страховка от профи ру
            cur_badges = json.loads(data_dirty['badges'][i])
            insurance = None
            contract = None

            for badge in cur_badges:
                if badge['type'] == 'insurance':
                    insurance = badge['text']
                if badge['type'] == 'contract':
                    contract = badge['text']

            ## хакнули скоры от профи ру
            cur_scores = json.loads(data_dirty['scores'][i])
            cur_score = cur_scores['score']

            ## когда мастер зарегистровался на профи ру
            cur_listing = json.loads(data_dirty['assembledInfoListing'][i])
            profi_ru_start = None
            for data in cur_listing:
                if data['type'] == 'INFO':
                    cur_fact = data['oioFact']
                    if "На сервисе с"in cur_fact['fact']['title']:
                        profi_ru_start = (cur_fact['fact']['title'])

            # Сборка данных строки
            row = {
                "master_id": master_id,
                "docs_verified": docs_verified,
                "gender": gender,
                "guarantee": master_garantee,
                "rating": mean_rating,
                "reviews_count": reviews_count,
                "experience_education": experience_education,
                "is_highly_praised": mark_hvalyat,
                "is_certified": work_cert,
                "price_socket": socket_price,
                "suitabilityHints": suit_hint,
                "discount": discount,
                "insurance": insurance,
                "contract": contract,
                "cur_score": cur_score,
                "profi_ru_start": profi_ru_start,
                "album_count": album_count,
                "photos_count": photos_count
            }
            rows.append(row)

        except Exception as e:
            print(f"Критическая ошибка на строке {i}: {e}")
            rows.append({})
    return pd.DataFrame(rows)

In [18]:
df1 = make_dataset(pd.read_csv('kazan_kirov.csv'))
df1.head(10)

электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
ремонт розеток
перенос розетки
электрика
электрика
электрика
установка розетки
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.591576,None,0,9
1,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.353000,None,0,8
2,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.299670,None,3,45
3,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.162056,None,0,1
4,https://profi.ru/profile/ScherbakovFV/,True,MALE,Нет гарантии,"5,0",28,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.671444,На сервисе с мая 2021 г. (5 лет),0,1
5,https://profi.ru/profile/BurhanovII2/,True,MALE,Нет гарантии,"5,0",37,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,100.0,Нет отзывов по вашей услуге,NaN,None,None,50.645668,На сервисе с сентября 2021 г. (4 года),0,0
6,https://profi.ru/profile/GalimomRR/,False,MALE,Нет гарантии,"4,50",18,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер-универ...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.637787,None,0,8
7,https://profi.ru/profile/SalikhovIK/,False,MALE,По договоренности,"4,82",90,"[{""type"": ""UGC1"", ""content"": ""<p>Являюсь офици...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.633846,None,0,4
8,https://profi.ru/profile/PikushevVV/,True,MALE,Нет гарантии,"5,0",40,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.630272,None,5,0
9,https://profi.ru/profile/MihailovSO2/,True,None,По договоренности,"4,90",41,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,Договор,50.613464,None,0,9

In [19]:
df2 = make_dataset(pd.read_csv('kazan_novosavinovski_place.csv'))
df2

электрика
установка розетки
электрика
электрика
перенос розетки
электрика
установка розетки
электрика
электрика
ремонт розеток
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.624840,None,0,9
1,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.430550,None,0,8
2,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.350975,На сервисе с сентября 2025 г,0,0
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.296684,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.157930,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,https://profi.ru/profile/SultanovIR5/,True,MALE,Нет гарантии,"5,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Электромонтаж...",False,False,NaN,None,NaN,None,None,50.702470,None,0,4
203,https://profi.ru/profile/KushkaIU/,False,MALE,По договоренности,"4,65",147,"[{""type"": ""UGC1"", ""content"": ""<p>Меня зовут Иг...",False,False,1000.0,None,10.0,None,None,50.702324,None,0,4
204,https://profi.ru/profile/StalbekUK/,True,FEMALE,Нет гарантии,"5,0",4,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.701340,None,0,0
205,https://profi.ru/profile/ZiyautdinovFZ/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.700935,На сервисе с марта 2025 г. (1 год),0,0
206,https://profi.ru/profile/ShavaleyevAF/,True,MALE,Нет гарантии,"4,33",6,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.700550,На сервисе с ноября 2024 г. (1 год),0,0

In [20]:
df3 = make_dataset(pd.read_csv('kazan_aviastroitelni_place.csv'))
df3

электрика
электрика
ремонт розеток
электрика
ремонт розеток
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.632810,None,0,9
1,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.351845,None,0,8
2,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.293440,None,3,45
3,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.150185,None,0,1
4,https://profi.ru/profile/ScherbakovFV/,True,MALE,Нет гарантии,"5,0",28,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.667747,На сервисе с мая 2021 г. (5 лет),0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,https://profi.ru/profile/ShavaleyevAF/,True,MALE,Нет гарантии,"4,33",6,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.621260,На сервисе с ноября 2024 г. (1 год),0,0
200,https://profi.ru/profile/DemyanovVV3/,True,None,Нет гарантии,"4,98",145,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,10.0,None,None,50.621025,None,0,21
201,https://profi.ru/profile/MinnigareyevII/,True,MALE,Нет гарантии,"5,0",5,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.620476,На сервисе с июня 2024 г. (1 год),0,22
202,https://profi.ru/profile/ValiullinMF2/,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p><strong>Опыт ...",False,False,150.0,None,NaN,None,None,50.619820,None,0,16
203,https://profi.ru/profile/AkhmetzyanovRR13/,True,MALE,Нет гарантии,"4,67",9,"[{""type"": ""UGC1"", ""content"": ""<p>Профессиональ...",False,False,NaN,Нет отзывов по вашей услуге,15.0,None,None,50.619568,None,0,0

In [21]:
df4 = make_dataset(pd.read_csv('kazan_privolzski_1_os.csv'))
df4

электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
ремонт розеток
электрика
электрика
электрика
электрика
перенос розетки
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.616270,None,0,9
1,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.406430,На сервисе с сентября 2025 г,0,0
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.333664,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.274400,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.108080,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,https://profi.ru/profile/GabdurakhmanovRV/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.800020,На сервисе с октября 2025 г,0,0
200,https://profi.ru/profile/BikulovEN/,True,MALE,Нет гарантии,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Универсал, за...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.800020,На сервисе с июня 2022 г. (3 года),0,5
201,https://profi.ru/profile/GanskiiVV/,True,MALE,Нет гарантии,"5,0",27,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.800020,На сервисе с сентября 2020 г. (5 лет),0,0
202,https://profi.ru/profile/GilmanovRF3/,True,None,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Занимаюсь эле...",False,False,NaN,None,NaN,None,None,50.800020,None,12,96
203,https://profi.ru/profile/MarkovPK/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Услуги элeктp...",False,False,1000.0,None,NaN,None,None,50.800020,None,0,2

In [22]:
df5 = make_dataset(pd.read_csv('kazan_privolzski_1_place.csv'))
df5

электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.616270,None,0,9
1,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.406430,На сервисе с сентября 2025 г,0,0
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.333664,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.274400,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.108080,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,https://profi.ru/profile/ShigabievFN/,True,MALE,Нет гарантии,"5,0",6,"[{""type"": ""UGC1"", ""content"": ""<p>Опыт больше 8...",False,False,NaN,None,NaN,None,None,50.628900,На сервисе с апреля 2021 г. (5 лет),0,17
206,https://profi.ru/profile/MelikovSR4/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.628517,На сервисе с февраля 2022 г. (4 года),0,0
207,https://profi.ru/profile/KayumovEA2/,True,None,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Опыт<...",False,False,NaN,None,NaN,None,None,50.628216,None,1,0
208,https://profi.ru/profile/AlekseevAA190/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.627247,На сервисе с ноября 2020 г. (5 лет),0,20
209,https://profi.ru/profile/MarkelovIV5/,True,MALE,Нет гарантии,"5,0",11,"[{""type"": ""INFO"", ""content"": ""<p><strong>Опыт<...",False,False,NaN,None,NaN,None,None,50.626812,None,2,17

In [23]:
df6 = make_dataset(pd.read_csv('kazan_privolzski_1_pop.csv'))
df6

электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
ремонт розеток
перенос розетки
установка розетки
электрика
электрика
установка розетки
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.616270,None,0,9
1,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.406430,На сервисе с сентября 2025 г,0,0
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.333664,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.274400,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.108080,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,https://profi.ru/profile/ShigabutdinovIE/,True,MALE,"«Договор подряда, и гарантия на работы до 10 лет»","4,78",18,"[{""type"": ""UGC1"", ""content"": ""<p>Делаю аккурат...",False,False,NaN,Мало отзывов по вашей услуге,5.0,None,None,50.340683,На сервисе с февраля 2019 г. (7 лет),0,0
194,https://profi.ru/profile/ButakovIN/,True,MALE,Нет гарантии,"4,82",100,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.338573,На сервисе с апреля 2019 г. (7 лет),0,0
195,https://profi.ru/profile/KamaletdinovAR/,False,MALE,По договоренности,"4,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Мы&nbsp;облад...",False,False,100.0,None,NaN,None,None,50.338120,None,0,1
196,https://profi.ru/profile/GumerovRR27/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Электромонтаж...",False,False,NaN,None,NaN,None,None,50.337710,None,3,0
197,https://profi.ru/profile/GalumyanAV/,True,MALE,По договоренности,"4,95",501,"[{""type"": ""UGC1"", ""content"": ""<p>Приеду к&nbsp...",False,False,NaN,None,NaN,None,None,50.337210,None,6,8

In [24]:
df7 = make_dataset(pd.read_csv('kazan_privolzski_2_place.csv'))
df7

электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.618576,None,0,9
1,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.396260,На сервисе с сентября 2025 г,0,0
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.317260,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.262930,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.098460,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,https://profi.ru/profile/NusamiyevKS/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.578648,На сервисе с июля 2025 г,0,0
206,https://profi.ru/profile/PatskovGV/,False,MALE,По договоренности,"4,76",25,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,Мало отзывов по вашей услуге,10.0,None,Договор,50.578632,На сервисе с декабря 2025 г,0,0
207,https://profi.ru/profile/FayzrakhmanovAR/,True,MALE,Нет гарантии,"5,0",8,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.578087,На сервисе с октября 2024 г. (1 год),0,9
208,https://profi.ru/profile/FayzullinRI2/,True,MALE,Нет гарантии,"5,0",1,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.578045,None,0,0
209,https://profi.ru/profile/ZalaltdinovIM/,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Частный масте...",False,False,NaN,None,NaN,None,None,50.578045,None,0,0

In [25]:
df8 = make_dataset(pd.read_csv('kazan_sovetski_1_place.csv'))
df8

электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
установка розетки
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
ремонт розеток
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.612580,None,0,9
1,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.362110,На сервисе с сентября 2025 г,0,0
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.352990,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.276535,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.105660,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,https://profi.ru/profile/LipskiyYS/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.665690,На сервисе с января 2026 г,0,0
209,https://profi.ru/profile/AzimovAG12/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.664112,На сервисе с февраля 2025 г. (1 год),0,0
210,https://profi.ru/profile/EsenbaevMB/,False,MALE,«2 года»,"4,97",142,"[{""type"": ""UGC1"", ""content"": ""<p>Наше отличие ...",False,False,NaN,None,NaN,None,Договор,50.663990,None,0,44
211,https://profi.ru/profile/GolubevAE12/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.663452,На сервисе с апреля 2026 г,0,0
212,https://profi.ru/profile/VorobyevDI11/,True,MALE,Нет гарантии,"4,0",4,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер широко...",False,False,NaN,None,15.0,None,None,50.662373,None,0,10

In [26]:
df9 = make_dataset(pd.read_csv('kazan_sovetski_2_place.csv'))
df9

электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.620450,None,0,9
1,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.353750,На сервисе с сентября 2025 г,0,0
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.340910,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.268760,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.095650,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,https://profi.ru/profile/VildanovIA2/,True,MALE,Нет гарантии,"4,99",84,"[{""type"": ""INFO"", ""content"": ""<p><strong>Опыт<...",False,False,NaN,None,NaN,None,None,50.551220,None,0,0
209,https://profi.ru/profile/NigamatzyanovMR/,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p><strong>Опыт ...",False,False,NaN,None,NaN,None,None,50.551210,На сервисе с февраля 2025 г. (1 год),0,9
210,https://profi.ru/profile/BabushkinDA/,True,MALE,Нет гарантии,"5,0",6,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,1500.0,Мало отзывов по вашей услуге,NaN,None,None,50.551132,На сервисе с сентября 2018 г. (7 лет),0,0
211,https://profi.ru/profile/AbdullinAM9/,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p><strong>Опыт<...",False,False,NaN,None,NaN,None,None,50.550365,На сервисе с ноября 2024 г. (1 год),0,7
212,https://profi.ru/profile/KhafizovRI5/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.549007,None,0,0

In [27]:
df10 = make_dataset(pd.read_csv('kazan_vahitovski_place.csv'))
df10

электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
электрика
перенос розетки
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.618520,None,0,9
1,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.364940,На сервисе с сентября 2025 г,0,0
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.352974,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.285230,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.147354,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,https://profi.ru/profile/GayanovRT/,True,MALE,Нет гарантии,"4,81",16,"[{""type"": ""UGC1"", ""content"": ""<p>Опыт в&nbsp;с...",False,False,600.0,None,10.0,None,None,50.697227,None,0,12
206,https://profi.ru/profile/MashchenkoDA3/,True,MALE,Нет гарантии,"5,0",15,"[{""type"": ""UGC1"", ""content"": ""<p>Я, пpoфeссион...",False,False,500.0,None,10.0,None,None,50.696873,На сервисе с апреля 2025 г. (1 год),0,10
207,https://profi.ru/profile/KonyukhovSV/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>&#9989; ЧЕМ О...",False,False,NaN,None,NaN,None,None,50.696648,На сервисе с марта 2023 г. (3 года),1,13
208,https://profi.ru/profile/YershovVS11/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.696648,None,0,0
209,https://profi.ru/profile/VahoninAM/,True,MALE,Нет гарантии,"5,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Мы&nbsp;заним...",False,False,NaN,None,NaN,None,None,50.695835,На сервисе с ноября 2020 г. (5 лет),0,8

In [28]:
df11 = make_dataset(pd.read_csv('kazan_mosk_best.csv'))
df11

электрика
электрика
электрика
установка розетки
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
перенос розетки
электрика
установка розетки
ремонт розеток
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.605095,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.501430,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.362150,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.297860,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.172070,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,https://profi.ru/profile/BlotskiiEB/,True,MALE,Нет гарантии,"4,75",8,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю 10 ле...",False,False,300.0,None,NaN,None,None,50.336536,На сервисе с сентября 2020 г. (5 лет),0,0
194,https://profi.ru/profile/BatanevMA/,True,MALE,По договоренности,"4,90",29,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,Договор,50.336470,На сервисе с января 2022 г. (4 года),5,94
195,https://profi.ru/profile/AmirkhanovFI/,True,None,Нет гарантии,"4,50",2,"[{""type"": ""UGC1"", ""content"": ""<p>20лет стажа м...",False,False,NaN,None,NaN,None,None,50.335810,На сервисе с ноября 2021 г. (4 года),0,5
196,https://profi.ru/profile/GafiyatulinII/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Опыт ...",False,False,500.0,None,NaN,None,None,50.334130,None,0,0
197,https://profi.ru/profile/GabitovRR3/,True,MALE,Нет гарантии,"5,0",6,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;отдело...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.333675,На сервисе с апреля 2019 г. (7 лет),0,1

In [29]:
df12 = make_dataset(pd.read_csv('kazan_mosk2.csv'))
df12

электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
перенос розетки
электрика
ремонт розеток
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.605095,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.501430,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.362150,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.297860,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.172070,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,https://profi.ru/profile/LatipovII4/,True,MALE,Нет гарантии,"5,0",15,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.730476,На сервисе с октября 2025 г,0,0
204,https://profi.ru/profile/YelchiyevRM/,True,MALE,Нет гарантии,"5,0",1,"[{""type"": ""INFO"", ""content"": ""<p><strong>Опыт<...",False,False,NaN,None,NaN,None,None,50.729050,None,0,0
205,https://profi.ru/profile/BystrovAF/,True,MALE,Нет гарантии,"5,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Всем Привет! ...",False,False,NaN,None,NaN,None,None,50.728046,None,0,2
206,https://profi.ru/profile/KuzembayevGM/,True,MALE,«Гарантия 6 месяцев с окончания работ»,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Занимаюсь ост...",False,False,NaN,None,10.0,None,None,50.727787,На сервисе с октября 2024 г. (1 год),0,0
207,https://profi.ru/profile/VasilyevAA208/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.726970,None,0,10

In [30]:
df13 = make_dataset(pd.read_csv('kazan_sovetski_pop.csv'))
df13

электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
установка розетки
перенос розетки
электрика
электрика
ремонт розеток
электрика
электрика
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.626366,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.620140,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.427734,None,0,8
3,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.349690,На сервисе с сентября 2025 г,0,0
4,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.297066,None,3,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,https://profi.ru/profile/GaripovRA4/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.351920,На сервисе с апреля 2019 г. (7 лет),0,0
195,https://profi.ru/profile/SultanovKR4/,True,MALE,Нет гарантии,"5,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Добрго времен...",False,False,NaN,None,NaN,None,None,50.350110,None,0,0
196,https://profi.ru/profile/SagdullinLF/,False,MALE,Нет гарантии,"5,0",8,"[{""type"": ""UGC1"", ""content"": ""<p>Занимаемся на...",False,False,300.0,Нет отзывов по вашей услуге,5.0,None,None,50.349890,None,0,15
197,https://profi.ru/profile/NaumetovRR/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.349850,На сервисе с марта 2026 г,0,6
198,https://profi.ru/profile/NikolayevDV51/,True,MALE,Нет гарантии,"5,0",5,"[{""type"": ""UGC1"", ""content"": ""<p>Электрик с&nb...",False,False,500.0,None,NaN,None,None,50.349810,None,0,21

In [31]:
df14 = make_dataset(pd.read_csv('kazan_novosavinovski_pop.csv'))
df14

электрика
установка розетки
ремонт розеток
перенос розетки
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
электрика
установка розетки
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.626366,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.620140,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.427734,None,0,8
3,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.349690,На сервисе с сентября 2025 г,0,0
4,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.297066,None,3,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,https://profi.ru/profile/MinnigareyevII/,True,MALE,Нет гарантии,"5,0",5,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.343113,На сервисе с июня 2024 г. (1 год),0,22
194,https://profi.ru/profile/SharafutdinovRE/,True,MALE,Нет гарантии,"4,99",67,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.342842,На сервисе с июля 2021 г. (4 года),0,0
195,https://profi.ru/profile/AlekseevAA190/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.342796,На сервисе с ноября 2020 г. (5 лет),0,20
196,https://profi.ru/profile/GalimovAA13/,True,MALE,Нет гарантии,"5,0",16,"[{""type"": ""UGC1"", ""content"": ""<p>В&nbsp;сфере ...",False,False,NaN,None,NaN,None,None,50.340770,None,0,7
197,https://profi.ru/profile/EgorovAA80/,True,MALE,Нет гарантии,"4,27",11,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день! ...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.340510,На сервисе с октября 2019 г. (6 лет),0,0

In [32]:
df15 = make_dataset(pd.read_csv('kazan_novosavinovski_os.csv'))
df15

электрика
установка розетки
электрика
электрика
электрика
ремонт розеток
установка розетки
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.626366,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.620140,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.427734,None,0,8
3,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.349690,На сервисе с сентября 2025 г,0,0
4,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.297066,None,3,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,https://profi.ru/profile/MinnigareyevII/,True,MALE,Нет гарантии,"5,0",5,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.800050,На сервисе с июня 2024 г. (1 год),0,22
128,https://profi.ru/profile/KarimovFF10/,True,MALE,Нет гарантии,"4,60",5,"[{""type"": ""INFO"", ""content"": ""<p><strong>Опыт<...",False,False,NaN,None,NaN,None,None,50.800050,None,0,16
129,https://profi.ru/profile/AhmadeevAA4/,True,None,Нет гарантии,"5,0",5,"[{""type"": ""UGC1"", ""content"": ""<p>7 лет.</p>\n<...",False,False,NaN,None,NaN,None,None,50.800050,None,0,5
130,https://profi.ru/profile/KhadiullinAN/,False,MALE,Нет гарантии,"5,0",5,"[{""type"": ""UGC1"", ""content"": ""<p>Здравcтвуйте,...",False,False,NaN,None,NaN,None,None,50.800050,На сервисе с ноября 2025 г,3,25
131,https://profi.ru/profile/BlotskiiEB/,True,MALE,Нет гарантии,"4,75",8,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю 10 ле...",False,False,300.0,None,NaN,None,None,50.800050,На сервисе с сентября 2020 г. (5 лет),0,0

In [33]:
df16 = make_dataset(pd.read_csv('kazan_aviastroitelni_pop.csv'))
df16

электрика
ремонт розеток
электрика
установка розетки
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
перенос розетки
электрика
ремонт розеток
электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.632810,None,0,9
1,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.351845,None,0,8
2,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.293440,None,3,45
3,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.150185,None,0,1
4,https://profi.ru/profile/ScherbakovFV/,True,MALE,Нет гарантии,"5,0",28,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.667747,На сервисе с мая 2021 г. (5 лет),0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,https://profi.ru/profile/GaynullinII2/,True,None,Нет гарантии,"4,80",20,"[{""type"": ""UGC1"", ""content"": ""<p><strong>Опыт ...",False,False,NaN,None,NaN,None,None,50.324165,На сервисе с ноября 2023 г. (2 года),0,9
192,https://profi.ru/profile/AlekseyevaIA21/,True,MALE,Нет гарантии,"5,0",9,"[{""type"": ""UGC1"", ""content"": ""<p>Индивидуальны...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.324047,None,0,1
193,https://profi.ru/profile/KhairtdinovRI/,True,MALE,Нет гарантии,"5,0",5,"[{""type"": ""UGC1"", ""content"": ""<p>Профессиональ...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.322920,None,1,0
194,https://profi.ru/profile/TashevVV/,True,MALE,Нет гарантии,"5,0",10,"[{""type"": ""UGC1"", ""content"": ""<p>Здрaвcтвуйте,...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.321760,На сервисе с октября 2022 г. (3 года),0,1
195,https://profi.ru/profile/BatanevMA/,True,MALE,По договоренности,"4,90",29,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,Договор,50.321728,На сервисе с января 2022 г. (4 года),5,94

In [34]:
df17 = make_dataset(pd.read_csv('kazan_aviastroitelni_os.csv'))
df17

электрика
электрика
электрика
электрика
электрика
ремонт розеток
установка розетки
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
ремонт розеток
электрика
электрика
электрика
электрика
перенос розетки
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.632810,None,0,9
1,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.351845,None,0,8
2,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.293440,None,3,45
3,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.150185,None,0,1
4,https://profi.ru/profile/ScherbakovFV/,True,MALE,Нет гарантии,"5,0",28,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.667747,На сервисе с мая 2021 г. (5 лет),0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,https://profi.ru/profile/GilmanovRF3/,True,None,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Занимаюсь эле...",False,False,NaN,None,NaN,None,None,50.800020,None,12,96
202,https://profi.ru/profile/BikulovEN/,True,MALE,Нет гарантии,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Универсал, за...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.800020,На сервисе с июня 2022 г. (3 года),0,5
203,https://profi.ru/profile/ShigabutdinovIE/,True,MALE,"«Договор подряда, и гарантия на работы до 10 лет»","4,78",18,"[{""type"": ""UGC1"", ""content"": ""<p>Делаю аккурат...",False,False,NaN,Мало отзывов по вашей услуге,5.0,None,None,50.800020,На сервисе с февраля 2019 г. (7 лет),0,0
204,https://profi.ru/profile/GaripovRM5/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю в&nbs...",False,False,NaN,None,NaN,None,None,50.800020,На сервисе с августа 2024 г. (1 год),0,0
205,https://profi.ru/profile/GaffarovRR4/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.800020,На сервисе с ноября 2020 г. (5 лет),0,7

In [35]:
df18 = make_dataset(pd.read_csv('kazan_sovetski_os.csv'))
df18

электрика
электрика
установка розетки
электрика
электрика
электрика
установка розетки
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
ремонт розеток
электрика
электрика
электрика
электрика
электрика
перенос розетки
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.622110,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.546230,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/GerasimovPV7/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,600.0,None,NaN,Есть страховка,None,70.361590,На сервисе с сентября 2025 г,0,0
3,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.348080,None,0,8
4,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.275116,None,3,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,https://profi.ru/profile/BasyrovDS/,True,MALE,Нет гарантии,"4,73",15,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.800020,На сервисе с апреля 2025 г. (1 год),0,0
203,https://profi.ru/profile/ImanovRV/,True,MALE,«От 6 месяцев до 1 года»,"4,89",37,"[{""type"": ""UGC1"", ""content"": ""<p>Аккуратный, и...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.800020,None,5,22
204,https://profi.ru/profile/KhayrullinRR18/,True,MALE,Нет гарантии,"5,0",9,"[{""type"": ""UGC1"", ""content"": ""<h4>Здpaвcтвуйтe...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.800020,На сервисе с декабря 2024 г. (1 год),1,0
205,https://profi.ru/profile/GabdurakhmanovRV/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.800020,На сервисе с октября 2025 г,0,0
206,https://profi.ru/profile/MarkovPK/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Услуги элeктp...",False,False,1000.0,None,NaN,None,None,50.800020,None,0,2

In [36]:
df19 = make_dataset(pd.read_csv('kazan_admiral_pop.csv'))
df19

электрика
установка розетки
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
перенос розетки
установка розетки
ремонт розеток
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.636890,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.496310,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.344510,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.296970,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.165880,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,https://profi.ru/profile/ValeyevRI4/,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Комплексная о...",False,False,NaN,None,NaN,None,None,50.330635,На сервисе с апреля 2026 г,0,0
194,https://profi.ru/profile/AmirkhanovFI/,True,None,Нет гарантии,"4,50",2,"[{""type"": ""UGC1"", ""content"": ""<p>20лет стажа м...",False,False,NaN,None,NaN,None,None,50.330380,На сервисе с ноября 2021 г. (4 года),0,5
195,https://profi.ru/profile/DavletshinIF5/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.330063,None,0,0
196,https://profi.ru/profile/BatanevMA/,True,MALE,По договоренности,"4,90",29,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,Договор,50.328743,На сервисе с января 2022 г. (4 года),5,94
197,https://profi.ru/profile/GolubevAE12/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.328340,На сервисе с апреля 2026 г,0,0

In [37]:
df20 = make_dataset(pd.read_csv('kazan_admiral_os.csv'))
df20

электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
ремонт розеток
электрика
электрика
электрика
электрика
электрика
электрика
перенос розетки
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.63689,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.49631,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.34451,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.29697,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.16588,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,https://profi.ru/profile/MarkovPK/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Услуги элeктp...",False,False,1000.0,None,NaN,None,None,50.80002,None,0,2
200,https://profi.ru/profile/BikulovEN/,True,MALE,Нет гарантии,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Универсал, за...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.80002,На сервисе с июня 2022 г. (3 года),0,5
201,https://profi.ru/profile/ShigabutdinovIE/,True,MALE,"«Договор подряда, и гарантия на работы до 10 лет»","4,78",18,"[{""type"": ""UGC1"", ""content"": ""<p>Делаю аккурат...",False,False,NaN,Мало отзывов по вашей услуге,5.0,None,None,50.80002,На сервисе с февраля 2019 г. (7 лет),0,0
202,https://profi.ru/profile/MusiyenkoAV4/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Александр раб...",False,False,NaN,None,NaN,None,None,50.80002,На сервисе с апреля 2025 г. (1 год),0,9
203,https://profi.ru/profile/GaffarovRR4/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.80002,На сервисе с ноября 2020 г. (5 лет),0,7

In [38]:
df21 = make_dataset(pd.read_csv('kazan_admiral_place.csv'))
df21

электрика
электрика
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
перенос розетки
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.636890,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.496310,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.344510,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.296970,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.165880,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,https://profi.ru/profile/KuryaginAV/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.650127,На сервисе с августа 2025 г,0,0
204,https://profi.ru/profile/MurzenkovTI/,True,MALE,Нет гарантии,"5,0",11,"[{""type"": ""UGC1"", ""content"": ""<p>6 лет занимал...",False,False,NaN,Нет отзывов по вашей услуге,NaN,None,None,50.646935,На сервисе с мая 2025 г,0,3
205,https://profi.ru/profile/NigmatovRR2/,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Сопровождение...",False,False,NaN,None,NaN,None,None,50.646355,На сервисе с ноября 2022 г. (3 года),5,0
206,https://profi.ru/profile/GabishevAA2/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.646340,None,0,0
207,https://profi.ru/profile/PonomarevOV12/,True,MALE,Нет гарантии,"4,97",147,"[{""type"": ""UGC1"", ""content"": ""<p>Доброго време...",False,False,NaN,None,5.0,None,None,50.645280,None,0,10

In [39]:
df22 = make_dataset(pd.read_csv('kazan_vahitovski_os.csv'))
df22

электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
установка розетки
электрика
ремонт розеток
электрика
электрика
электрика
электрика
перенос розетки
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.63689,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.49631,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.34451,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.29697,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.16588,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,https://profi.ru/profile/GilmanovRF3/,True,None,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Занимаюсь эле...",False,False,NaN,None,NaN,None,None,50.80002,None,12,96
198,https://profi.ru/profile/BikulovEN/,True,MALE,Нет гарантии,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Универсал, за...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.80002,На сервисе с июня 2022 г. (3 года),0,5
199,https://profi.ru/profile/ShigabutdinovIE/,True,MALE,"«Договор подряда, и гарантия на работы до 10 лет»","4,78",18,"[{""type"": ""UGC1"", ""content"": ""<p>Делаю аккурат...",False,False,NaN,Мало отзывов по вашей услуге,5.0,None,None,50.80002,На сервисе с февраля 2019 г. (7 лет),0,0
200,https://profi.ru/profile/GaffarovRR4/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.80002,На сервисе с ноября 2020 г. (5 лет),0,7
201,https://profi.ru/profile/MusiyenkoAV4/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Александр раб...",False,False,NaN,None,NaN,None,None,50.80002,На сервисе с апреля 2025 г. (1 год),0,9

In [40]:
df23 = make_dataset(pd.read_csv('kazan_vahitovski.csv'))
df23

электрика
установка розетки
электрика
электрика
установка розетки
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
электрика
установка розетки
электрика
перенос розетки
установка розетки
ремонт розеток
электрика
электрика
электрика
электрика
электрика

,master_id,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/KraynovPV2/,True,MALE,Нет гарантии,"5,0",21,"[{""type"": ""UGC1"", ""content"": ""<p>Выполняю широ...",False,False,NaN,Мало отзывов по вашей услуге,10.0,Есть страховка,None,70.636890,None,0,9
1,https://profi.ru/profile/KaripovRF3/,True,MALE,Нет гарантии,"4,97",141,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,None,5.0,Есть страховка,None,70.496310,На сервисе с июля 2025 г,4,47
2,https://profi.ru/profile/SabirzanovAS/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Я&nbsp;— элек...",False,False,NaN,None,NaN,Есть страховка,None,70.344510,None,0,8
3,https://profi.ru/profile/LoginovNA2/,False,MALE,«1 год»,"5,0",13,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю с&nbs...",False,False,8000.0,None,5.0,Есть страховка,None,70.296970,None,3,45
4,https://profi.ru/profile/AlimovAA/,True,MALE,«1 год»,"4,99",616,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день д...",False,False,NaN,None,10.0,Есть страховка,None,70.165880,None,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,https://profi.ru/profile/ValeyevRI4/,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Комплексная о...",False,False,NaN,None,NaN,None,None,50.330635,На сервисе с апреля 2026 г,0,0
194,https://profi.ru/profile/AmirkhanovFI/,True,None,Нет гарантии,"4,50",2,"[{""type"": ""UGC1"", ""content"": ""<p>20лет стажа м...",False,False,NaN,None,NaN,None,None,50.330380,На сервисе с ноября 2021 г. (4 года),0,5
195,https://profi.ru/profile/DavletshinIF5/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.330063,None,0,0
196,https://profi.ru/profile/BatanevMA/,True,MALE,По договоренности,"4,90",29,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,Договор,50.328743,На сервисе с января 2022 г. (4 года),5,94
197,https://profi.ru/profile/GolubevAE12/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.328340,На сервисе с апреля 2026 г,0,0

In [41]:
all_data_id = set()
all_data_id = all_data_id | set(df1['master_id'])
all_data_id = all_data_id | set(df2['master_id'])
all_data_id = all_data_id | set(df3['master_id'])
all_data_id = all_data_id | set(df4['master_id'])
all_data_id = all_data_id | set(df5['master_id'])
all_data_id = all_data_id | set(df6['master_id'])
all_data_id = all_data_id | set(df7['master_id'])
all_data_id = all_data_id | set(df8['master_id'])
all_data_id = all_data_id | set(df9['master_id'])
all_data_id = all_data_id | set(df10['master_id'])
all_data_id = all_data_id | set(df11['master_id'])
all_data_id = all_data_id | set(df12['master_id'])
all_data_id = all_data_id | set(df13['master_id'])
all_data_id = all_data_id | set(df14['master_id'])
all_data_id = all_data_id | set(df15['master_id'])
all_data_id = all_data_id | set(df16['master_id'])
all_data_id = all_data_id | set(df17['master_id'])
all_data_id = all_data_id | set(df18['master_id'])
all_data_id = all_data_id | set(df19['master_id'])
all_data_id = all_data_id | set(df20['master_id'])
all_data_id = all_data_id | set(df21['master_id'])
all_data_id = all_data_id | set(df22['master_id'])
all_data_id = all_data_id | set(df23['master_id'])

In [42]:
len(all_data_id)

743

In [ ]:
## свалим все в одну кучу
all_data = pd.concat([df1, df2, df3, df3, df4, df5,
                df6, df7, df8, df9, df10, df11, df12,
                df13, df14, df15, df16, df17, df18,
                df19, df20, df21, df22, df23], axis=0).drop_duplicates()

In [44]:
all_data = all_data.reset_index() ## индекс это ранг в выдаче

In [ ]:
## сгруппируем по ID
all_data_final = all_data.groupby(by=['master_id'], as_index=False).agg({
    'index': 'mean', ## берем средний ранг для человека для разных поисков
    'docs_verified': lambda x: x.mode().iloc[0] if not x.mode().empty else None, ## кастомная мода для группировки в пандасе
    'gender': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'guarantee': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'rating': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'reviews_count': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'experience_education': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'is_highly_praised': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'is_certified': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'price_socket': 'mean',  ## берем среднюю цену для разных поисков
    'suitabilityHints': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'discount': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'insurance': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'contract': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'cur_score': 'mean',  ## берем средний скор профи ру для разных поисков
    'profi_ru_start': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'album_count': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'photos_count': lambda x: x.mode().iloc[0] if not x.mode().empty else None
})
all_data_final['index'] = round(all_data_final['index'], 0) ## округлим индекс до целого

In [48]:
all_data_final

,master_id,index,docs_verified,gender,guarantee,rating,reviews_count,experience_education,is_highly_praised,is_certified,price_socket,suitabilityHints,discount,insurance,contract,cur_score,profi_ru_start,album_count,photos_count
0,https://profi.ru/profile/AbdullinAA22/,110.0,True,None,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.679233,На сервисе с июня 2025 г,0,0
1,https://profi.ru/profile/AbdullinAM9/,158.0,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p><strong>Опыт<...",False,False,NaN,None,NaN,None,None,50.700671,На сервисе с ноября 2024 г. (1 год),0,7
2,https://profi.ru/profile/AbdullinAN2/,131.0,True,MALE,По договоренности,"4,73",15,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,Мало отзывов по вашей услуге,NaN,None,None,50.761180,На сервисе с октября 2020 г. (5 лет),0,2
3,https://profi.ru/profile/AbdullinLR/,39.0,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.500441,None,0,0
4,https://profi.ru/profile/AbrashevYI/,85.0,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.782032,None,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738,https://profi.ru/profile/ZinnurovDI2/,108.0,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте,...",False,False,NaN,None,NaN,None,None,50.539320,None,2,3
739,https://profi.ru/profile/ZiyautdinovFZ/,95.0,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.787963,На сервисе с марта 2025 г. (1 год),0,0
740,https://profi.ru/profile/ZlobinAA22/,48.0,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,None,NaN,None,None,50.798721,На сервисе с сентября 2025 г,0,0
741,https://profi.ru/profile/ZvitseviLA/,76.0,True,MALE,Нет гарантии,"4,76",68,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,None,NaN,None,None,50.753450,None,0,0
742,https://profi.ru/profile/user5845441/,98.0,False,MALE,По договоренности,"4,25",16,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,10000.0,None,10.0,None,Договор,50.651782,На сервисе с августа 2022 г. (3 года),2,13

In [56]:
all_data_final.to_csv('all_data_final.csv', index=False)

### Разметка опыта и образования через Gigachat

In [51]:
#!pip install gigachat
from gigachat import GigaChat

#!pip install razdel
import warnings
warnings.filterwarnings('ignore')

In [ ]:
AUTH_KEY = '' ## не-не, ключ не дам, придется поверить наслово

In [ ]:
def label_data(text: str, giga: GigaChat):
    """Классификация текста через GigaChat."""

    # Формируем четкую инструкцию для модели
    prompt = ( """Ты опытный менеджер по подбору мастеров по установке розеток в городе Казань, отлично умеешь оценивать уровень образования и опыт работы мастеров.

#Задача
Оценить уровнь образования мастера и его опыт работы по описанию.

Уровень образования (в формате True/False - имеется ли у мастера образование этого уровня):
1. Профессиональное среднее образование: если мастер закончил техникум, коледж, ПТУ и т.д. включая аббревиатуры конкретных мест обучения, относящихся к профессиональному среднему образованию
2. Высшее образование: если мастер закончил университет, институт и т.д., включая аббревиатуры конкретных мест обучения, относящихся к высшему образованию


Опыт работы (в формате число или None):
Необходимо выделить сумму лет работы мастера. Учитывай, что сейчас 2026 год. То есть "опыт работы с 2021 года" означает 5 лет опыта работы. Верни только число лет работы.
Если опыт работы не указан, верни None

# Формат вывода

Выводи результат строго в формате JSON следующего вида

{'Профессиональное среднее образование': True / False,
 'Высшее образование': True / False,
 'Опыт работы': суммарное число лет работы (только число)}

# Пример:
Описание мастера:
'Казанский энергетический техникум, 2011–2014 гг. ИНК-Сервис занимался монтажом и обслуживанием электрооборудования, ремонтировал сантехнику , мебель , чистил снег, 2018–2025 гг.'

Правильный вывод:

{'Профессиональное среднее образование': True,
 'Высшее образование': False,
 'Опыт работы': 8}

Верни корректный JSON для описания мастера: """
f'{text}')
    try:
        response = giga.chat(prompt)
        content = response.choices[0].message.content

        # Находим JSON в ответе (на случай, если модель добавит лишний текст)
        start = content.find('{')
        end = content.rfind('}') + 1
        return json.loads(content[start:end])
    except Exception as e:
        return {"category": "Ошибка", "details": str(e)}

In [57]:
print("🚀 Начинаю разметку через GigaChat...")
dataset = list(all_data_final['experience_education'])
results = []

# verify_ssl_certs=False критичен, если у вас нет сертификатов Минцифры
with GigaChat(credentials=AUTH_KEY, verify_ssl_certs=False) as giga:
    for i, text in enumerate(dataset, 1):
        print(f'Обработка документа {i}...')
        label = label_data(text, giga)
        label['master_id'] = all_data_final.iloc[i - 1, 0]
        results.append(label)

🚀 Начинаю разметку через GigaChat...
Обработка документа 1...
Обработка документа 2...
Обработка документа 3...
Обработка документа 4...
Обработка документа 5...
Обработка документа 6...
Обработка документа 7...
Обработка документа 8...
Обработка документа 9...
Обработка документа 10...
Обработка документа 11...
Обработка документа 12...
Обработка документа 13...
Обработка документа 14...
Обработка документа 15...
Обработка документа 16...
Обработка документа 17...
Обработка документа 18...
Обработка документа 19...
Обработка документа 20...
Обработка документа 21...
Обработка документа 22...
Обработка документа 23...
Обработка документа 24...
Обработка документа 25...
Обработка документа 26...
Обработка документа 27...
Обработка документа 28...
Обработка документа 29...
Обработка документа 30...
Обработка документа 31...
Обработка документа 32...
Обработка документа 33...
Обработка документа 34...
Обработка документа 35...
Обработка документа 36...
Обработка документа 37...
Обработка документа 38...
Обработка документа 39...
Обработка документа 40...
Обработка документа 41...
Обработка документа 42...
Обработка документа 43...
Обработка документа 44...
Обработка документа 45...
Обработка документа 46...
Обработка документа 47...
Обработка документа 48...
Обработка документа 49...
Обработка документа 50...
Обработка документа 51...
Обработка документа 52...
Обработка документа 53...
Обработка документа 54...
Обработка документа 55...
Обработка документа 56...
Обработка документа 57...
Обработка документа 58...
Обработка документа 59...
Обработка документа 60...
Обработка документа 61...
Обработка документа 62...
Обработка документа 63...
Обработка документа 64...
Обработка документа 65...
Обработка документа 66...
Обработка документа 67...
Обработка документа 68...
Обработка документа 69...
Обработка документа 70...
Обработка документа 71...
Обработка документа 72...
Обработка документа 73...
Обработка документа 74...
Обработка документа 75...
Обработка документа 76...
Обработка документа 77...
Обработка документа 78...
Обработка документа 79...
Обработка документа 80...
Обработка документа 81...
Обработка документа 82...
Обработка документа 83...
Обработка документа 84...
Обработка документа 85...
Обработка документа 86...
Обработка документа 87...
Обработка документа 88...
Обработка документа 89...
Обработка документа 90...
Обработка документа 91...
Обработка документа 92...
Обработка документа 93...
Обработка документа 94...
Обработка документа 95...
Обработка документа 96...
Обработка документа 97...
Обработка документа 98...
Обработка документа 99...
Обработка документа 100...
Обработка документа 101...
Обработка документа 102...
Обработка документа 103...
Обработка документа 104...
Обработка документа 105...
Обработка документа 106...
Обработка документа 107...
Обработка документа 108...
Обработка документа 109...
Обработка документа 110...
Обработка документа 111...
Обработка документа 112...
Обработка документа 113...
Обработка документа 114...
Обработка документа 115...
Обработка документа 116...
Обработка документа 117...
Обработка документа 118...
Обработка документа 119...
Обработка документа 120...
Обработка документа 121...
Обработка документа 122...
Обработка документа 123...
Обработка документа 124...
Обработка документа 125...
Обработка документа 126...
Обработка документа 127...
Обработка документа 128...
Обработка документа 129...
Обработка документа 130...
Обработка документа 131...
Обработка документа 132...
Обработка документа 133...
Обработка документа 134...
Обработка документа 135...
Обработка документа 136...
Обработка документа 137...
Обработка документа 138...
Обработка документа 139...
Обработка документа 140...
Обработка документа 141...
Обработка документа 142...
Обработка документа 143...
Обработка документа 144...
Обработка документа 145...
Обработка документа 146...
Обработка документа 147...
Обработка документа 148...
Обработка документа 149...
Обработка документа 150...
Обработка документа 151...
Обработка документа 152...
Обработка документа 153...
Обработка документа 154...
Обработка документа 155...
Обработка документа 156...
Обработка документа 157...
Обработка документа 158...
Обработка документа 159...
Обработка документа 160...
Обработка документа 161...
Обработка документа 162...
Обработка документа 163...
Обработка документа 164...
Обработка документа 165...
Обработка документа 166...
Обработка документа 167...
Обработка документа 168...
Обработка документа 169...
Обработка документа 170...
Обработка документа 171...
Обработка документа 172...
Обработка документа 173...
Обработка документа 174...
Обработка документа 175...
Обработка документа 176...
Обработка документа 177...
Обработка документа 178...
Обработка документа 179...
Обработка документа 180...
Обработка документа 181...
Обработка документа 182...
Обработка документа 183...
Обработка документа 184...
Обработка документа 185...
Обработка документа 186...
Обработка документа 187...
Обработка документа 188...
Обработка документа 189...
Обработка документа 190...
Обработка документа 191...
Обработка документа 192...
Обработка документа 193...
Обработка документа 194...
Обработка документа 195...
Обработка документа 196...
Обработка документа 197...
Обработка документа 198...
Обработка документа 199...
Обработка документа 200...
Обработка документа 201...
Обработка документа 202...
Обработка документа 203...
Обработка документа 204...
Обработка документа 205...
Обработка документа 206...
Обработка документа 207...
Обработка документа 208...
Обработка документа 209...
Обработка документа 210...
Обработка документа 211...
Обработка документа 212...
Обработка документа 213...
Обработка документа 214...
Обработка документа 215...
Обработка документа 216...
Обработка документа 217...
Обработка документа 218...
Обработка документа 219...
Обработка документа 220...
Обработка документа 221...
Обработка документа 222...
Обработка документа 223...
Обработка документа 224...
Обработка документа 225...
Обработка документа 226...
Обработка документа 227...
Обработка документа 228...
Обработка документа 229...
Обработка документа 230...
Обработка документа 231...
Обработка документа 232...
Обработка документа 233...
Обработка документа 234...
Обработка документа 235...
Обработка документа 236...
Обработка документа 237...
Обработка документа 238...
Обработка документа 239...
Обработка документа 240...
Обработка документа 241...
Обработка документа 242...
Обработка документа 243...
Обработка документа 244...
Обработка документа 245...
Обработка документа 246...
Обработка документа 247...
Обработка документа 248...
Обработка документа 249...
Обработка документа 250...
Обработка документа 251...
Обработка документа 252...
Обработка документа 253...
Обработка документа 254...
Обработка документа 255...
Обработка документа 256...
Обработка документа 257...
Обработка документа 258...
Обработка документа 259...
Обработка документа 260...
Обработка документа 261...
Обработка документа 262...
Обработка документа 263...
Обработка документа 264...
Обработка документа 265...
Обработка документа 266...
Обработка документа 267...
Обработка документа 268...
Обработка документа 269...
Обработка документа 270...
Обработка документа 271...
Обработка документа 272...
Обработка документа 273...
Обработка документа 274...
Обработка документа 275...
Обработка документа 276...
Обработка документа 277...
Обработка документа 278...
Обработка документа 279...
Обработка документа 280...
Обработка документа 281...
Обработка документа 282...
Обработка документа 283...
Обработка документа 284...
Обработка документа 285...
Обработка документа 286...
Обработка документа 287...
Обработка документа 288...
Обработка документа 289...
Обработка документа 290...
Обработка документа 291...
Обработка документа 292...
Обработка документа 293...
Обработка документа 294...
Обработка документа 295...
Обработка документа 296...
Обработка документа 297...
Обработка документа 298...
Обработка документа 299...
Обработка документа 300...
Обработка документа 301...
Обработка документа 302...
Обработка документа 303...
Обработка документа 304...
Обработка документа 305...
Обработка документа 306...
Обработка документа 307...
Обработка документа 308...
Обработка документа 309...
Обработка документа 310...
Обработка документа 311...
Обработка документа 312...
Обработка документа 313...
Обработка документа 314...
Обработка документа 315...
Обработка документа 316...
Обработка документа 317...
Обработка документа 318...
Обработка документа 319...
Обработка документа 320...
Обработка документа 321...
Обработка документа 322...
Обработка документа 323...
Обработка документа 324...
Обработка документа 325...
Обработка документа 326...
Обработка документа 327...
Обработка документа 328...
Обработка документа 329...
Обработка документа 330...
Обработка документа 331...
Обработка документа 332...
Обработка документа 333...
Обработка документа 334...
Обработка документа 335...
Обработка документа 336...
Обработка документа 337...
Обработка документа 338...
Обработка документа 339...
Обработка документа 340...
Обработка документа 341...
Обработка документа 342...
Обработка документа 343...
Обработка документа 344...
Обработка документа 345...
Обработка документа 346...
Обработка документа 347...
Обработка документа 348...
Обработка документа 349...
Обработка документа 350...
Обработка документа 351...
Обработка документа 352...
Обработка документа 353...
Обработка документа 354...
Обработка документа 355...
Обработка документа 356...
Обработка документа 357...
Обработка документа 358...
Обработка документа 359...
Обработка документа 360...
Обработка документа 361...
Обработка документа 362...
Обработка документа 363...
Обработка документа 364...
Обработка документа 365...
Обработка документа 366...
Обработка документа 367...
Обработка документа 368...
Обработка документа 369...
Обработка документа 370...
Обработка документа 371...
Обработка документа 372...
Обработка документа 373...
Обработка документа 374...
Обработка документа 375...
Обработка документа 376...
Обработка документа 377...
Обработка документа 378...
Обработка документа 379...
Обработка документа 380...
Обработка документа 381...
Обработка документа 382...
Обработка документа 383...
Обработка документа 384...
Обработка документа 385...
Обработка документа 386...
Обработка документа 387...
Обработка документа 388...
Обработка документа 389...
Обработка документа 390...
Обработка документа 391...
Обработка документа 392...
Обработка документа 393...
Обработка документа 394...
Обработка документа 395...
Обработка документа 396...
Обработка документа 397...
Обработка документа 398...
Обработка документа 399...
Обработка документа 400...
Обработка документа 401...
Обработка документа 402...
Обработка документа 403...
Обработка документа 404...
Обработка документа 405...
Обработка документа 406...
Обработка документа 407...
Обработка документа 408...
Обработка документа 409...
Обработка документа 410...
Обработка документа 411...
Обработка документа 412...
Обработка документа 413...
Обработка документа 414...
Обработка документа 415...
Обработка документа 416...
Обработка документа 417...
Обработка документа 418...
Обработка документа 419...
Обработка документа 420...
Обработка документа 421...
Обработка документа 422...
Обработка документа 423...
Обработка документа 424...
Обработка документа 425...
Обработка документа 426...
Обработка документа 427...
Обработка документа 428...
Обработка документа 429...
Обработка документа 430...
Обработка документа 431...
Обработка документа 432...
Обработка документа 433...
Обработка документа 434...
Обработка документа 435...
Обработка документа 436...
Обработка документа 437...
Обработка документа 438...
Обработка документа 439...
Обработка документа 440...
Обработка документа 441...
Обработка документа 442...
Обработка документа 443...
Обработка документа 444...
Обработка документа 445...
Обработка документа 446...
Обработка документа 447...
Обработка документа 448...
Обработка документа 449...
Обработка документа 450...
Обработка документа 451...
Обработка документа 452...
Обработка документа 453...
Обработка документа 454...
Обработка документа 455...
Обработка документа 456...
Обработка документа 457...
Обработка документа 458...
Обработка документа 459...
Обработка документа 460...
Обработка документа 461...
Обработка документа 462...
Обработка документа 463...
Обработка документа 464...
Обработка документа 465...
Обработка документа 466...
Обработка документа 467...
Обработка документа 468...
Обработка документа 469...
Обработка документа 470...
Обработка документа 471...
Обработка документа 472...
Обработка документа 473...
Обработка документа 474...
Обработка документа 475...
Обработка документа 476...
Обработка документа 477...
Обработка документа 478...
Обработка документа 479...
Обработка документа 480...
Обработка документа 481...
Обработка документа 482...
Обработка документа 483...
Обработка документа 484...
Обработка документа 485...
Обработка документа 486...
Обработка документа 487...
Обработка документа 488...
Обработка документа 489...
Обработка документа 490...
Обработка документа 491...
Обработка документа 492...
Обработка документа 493...
Обработка документа 494...
Обработка документа 495...
Обработка документа 496...
Обработка документа 497...
Обработка документа 498...
Обработка документа 499...
Обработка документа 500...
Обработка документа 501...
Обработка документа 502...
Обработка документа 503...
Обработка документа 504...
Обработка документа 505...
Обработка документа 506...
Обработка документа 507...
Обработка документа 508...
Обработка документа 509...
Обработка документа 510...
Обработка документа 511...
Обработка документа 512...
Обработка документа 513...
Обработка документа 514...
Обработка документа 515...
Обработка документа 516...
Обработка документа 517...
Обработка документа 518...
Обработка документа 519...
Обработка документа 520...
Обработка документа 521...
Обработка документа 522...
Обработка документа 523...
Обработка документа 524...
Обработка документа 525...
Обработка документа 526...
Обработка документа 527...
Обработка документа 528...
Обработка документа 529...
Обработка документа 530...
Обработка документа 531...
Обработка документа 532...
Обработка документа 533...
Обработка документа 534...
Обработка документа 535...
Обработка документа 536...
Обработка документа 537...
Обработка документа 538...
Обработка документа 539...
Обработка документа 540...
Обработка документа 541...
Обработка документа 542...
Обработка документа 543...
Обработка документа 544...
Обработка документа 545...
Обработка документа 546...
Обработка документа 547...
Обработка документа 548...
Обработка документа 549...
Обработка документа 550...
Обработка документа 551...
Обработка документа 552...
Обработка документа 553...
Обработка документа 554...
Обработка документа 555...
Обработка документа 556...
Обработка документа 557...
Обработка документа 558...
Обработка документа 559...
Обработка документа 560...
Обработка документа 561...
Обработка документа 562...
Обработка документа 563...
Обработка документа 564...
Обработка документа 565...
Обработка документа 566...
Обработка документа 567...
Обработка документа 568...
Обработка документа 569...
Обработка документа 570...
Обработка документа 571...
Обработка документа 572...
Обработка документа 573...
Обработка документа 574...
Обработка документа 575...
Обработка документа 576...
Обработка документа 577...
Обработка документа 578...
Обработка документа 579...
Обработка документа 580...
Обработка документа 581...
Обработка документа 582...
Обработка документа 583...
Обработка документа 584...
Обработка документа 585...
Обработка документа 586...
Обработка документа 587...
Обработка документа 588...
Обработка документа 589...
Обработка документа 590...
Обработка документа 591...
Обработка документа 592...
Обработка документа 593...
Обработка документа 594...
Обработка документа 595...
Обработка документа 596...
Обработка документа 597...
Обработка документа 598...
Обработка документа 599...
Обработка документа 600...
Обработка документа 601...
Обработка документа 602...
Обработка документа 603...
Обработка документа 604...
Обработка документа 605...
Обработка документа 606...
Обработка документа 607...
Обработка документа 608...
Обработка документа 609...
Обработка документа 610...
Обработка документа 611...
Обработка документа 612...
Обработка документа 613...
Обработка документа 614...
Обработка документа 615...
Обработка документа 616...
Обработка документа 617...
Обработка документа 618...
Обработка документа 619...
Обработка документа 620...
Обработка документа 621...
Обработка документа 622...
Обработка документа 623...
Обработка документа 624...
Обработка документа 625...
Обработка документа 626...
Обработка документа 627...
Обработка документа 628...
Обработка документа 629...
Обработка документа 630...
Обработка документа 631...
Обработка документа 632...
Обработка документа 633...
Обработка документа 634...
Обработка документа 635...
Обработка документа 636...
Обработка документа 637...
Обработка документа 638...
Обработка документа 639...
Обработка документа 640...
Обработка документа 641...
Обработка документа 642...
Обработка документа 643...
Обработка документа 644...
Обработка документа 645...
Обработка документа 646...
Обработка документа 647...
Обработка документа 648...
Обработка документа 649...
Обработка документа 650...
Обработка документа 651...
Обработка документа 652...
Обработка документа 653...
Обработка документа 654...
Обработка документа 655...
Обработка документа 656...
Обработка документа 657...
Обработка документа 658...
Обработка документа 659...
Обработка документа 660...
Обработка документа 661...
Обработка документа 662...
Обработка документа 663...
Обработка документа 664...
Обработка документа 665...
Обработка документа 666...
Обработка документа 667...
Обработка документа 668...
Обработка документа 669...
Обработка документа 670...
Обработка документа 671...
Обработка документа 672...
Обработка документа 673...
Обработка документа 674...
Обработка документа 675...
Обработка документа 676...
Обработка документа 677...
Обработка документа 678...
Обработка документа 679...
Обработка документа 680...
Обработка документа 681...
Обработка документа 682...
Обработка документа 683...
Обработка документа 684...
Обработка документа 685...
Обработка документа 686...
Обработка документа 687...
Обработка документа 688...
Обработка документа 689...
Обработка документа 690...
Обработка документа 691...
Обработка документа 692...
Обработка документа 693...
Обработка документа 694...
Обработка документа 695...
Обработка документа 696...
Обработка документа 697...
Обработка документа 698...
Обработка документа 699...
Обработка документа 700...
Обработка документа 701...
Обработка документа 702...
Обработка документа 703...
Обработка документа 704...
Обработка документа 705...
Обработка документа 706...
Обработка документа 707...
Обработка документа 708...
Обработка документа 709...
Обработка документа 710...
Обработка документа 711...
Обработка документа 712...
Обработка документа 713...
Обработка документа 714...
Обработка документа 715...
Обработка документа 716...
Обработка документа 717...
Обработка документа 718...
Обработка документа 719...
Обработка документа 720...
Обработка документа 721...
Обработка документа 722...
Обработка документа 723...
Обработка документа 724...
Обработка документа 725...
Обработка документа 726...
Обработка документа 727...
Обработка документа 728...
Обработка документа 729...
Обработка документа 730...
Обработка документа 731...
Обработка документа 732...
Обработка документа 733...
Обработка документа 734...
Обработка документа 735...
Обработка документа 736...
Обработка документа 737...
Обработка документа 738...
Обработка документа 739...
Обработка документа 740...
Обработка документа 741...
Обработка документа 742...
Обработка документа 743...

In [58]:
data_labeled = pd.DataFrame(results).drop(['category', 'details'], axis=1)
data_labeled

,Профессиональное среднее образование,Высшее образование,Опыт работы,master_id
0,True,False,7.0,https://profi.ru/profile/AbdullinAA22/
1,True,False,8.0,https://profi.ru/profile/AbdullinAM9/
2,True,False,6.0,https://profi.ru/profile/AbdullinAN2/
3,False,True,NaN,https://profi.ru/profile/AbdullinLR/
4,True,False,7.0,https://profi.ru/profile/AbrashevYI/
...,...,...,...,...
738,False,False,23.0,https://profi.ru/profile/ZinnurovDI2/
739,True,False,1.0,https://profi.ru/profile/ZiyautdinovFZ/
740,True,False,7.0,https://profi.ru/profile/ZlobinAA22/
741,True,False,10.0,https://profi.ru/profile/ZvitseviLA/
742,False,True,4.0,https://profi.ru/profile/user5845441/

In [61]:
all_data_final_llm = pd.concat([data_labeled, all_data_final], axis=1)
all_data_final_llm.rename(columns={'Профессиональное среднее образование': 'has_secondary_education', 'Высшее образование': 'has_higher_education', 'Опыт работы': 'work_experience'}, inplace=True)

In [67]:
all_data_final_llm = all_data_final_llm.drop('experience_education',axis=1)

In [69]:
all_data_final_llm.to_csv('all_data_final_llm.csv', index=False)

In [71]:
all_data_final_llm.shape

(743, 22)