In [2]:
import pandas as pd
import json
import re

In [3]:
data = pd.read_csv('moskva_tennis_full.csv')
data

,_Лет_на_сайте,_Ссылка,_Стаж,abbreviatedName,adaptiveReviews,albums,assembledInfoListing,audio,avatar,badges,...,wantsNewOrders,workplaces,Выезд к клиенту,Дополнительная информация,Достижения,О себе,Образование,Опыт,Работает дистанционно,Услуги и цены
0,—,https://profi.ru/profile/BazylevPN/,—,Петр Б.,"{""review"": ""Хочу сказать огромное спасибо Петр...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>. Опыт в&nbsp...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/905b5c0eb81347d7b...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""B...","Зеленоград, Химки, Юрлово,\nВодный стадион,\nВ...",NaN,NaN,. Опыт в теннисе: 20 лет.\n. Действующий спорт...,NaN,На сервисе с декабря 2025 г\nФотографии7\nВсе ...,Нет,"–15%\nНа Первое Занятие, напомните промокод «Л..."
1,—,https://profi.ru/profile/TsyplyakovKA/,—,Константин Ц.,"{""review"": ""Хочу выразить огромную благодарнос...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Считаю важным...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/b5c31e59e0af44b1b...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""T...","Арбатско-Покровская,\nБКЛ,\nБутовская,\nЗамоск...",NaN,NaN,Считаю важным индивидуальный подход к каждому ...,Пермский государственный гуманитарно-педагогич...,На сервисе с апреля 2016 г. (10 лет)\nФотограф...,Нет,–50%\nКлиент оплачивает аренду корта . 50% тре...
2,—,https://profi.ru/profile/LetunovaMA/,—,Мария Л.,"{""review"": ""Спасибо Марии за занятия. Учусь с ...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/a5aa0fb6e32044d9a...,"[{""type"": ""unverified"", ""text"": ""Паспорт не пр...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],"Академический район, Алексеевский район, Алтуф...",NaN,Мастер спорта России по теннису2024 г.\nФотогр...,"Здравствуйте! Меня зовут Мария, я тренер и спа...",NaN,На сервисе с сентября 2024 г. (1 год),Нет,Большой теннис\nИндивидуальное занятие- 2000-3...
3,—,https://profi.ru/profile/EliseevDV2/,—,Дмитрий Е.,"{""review"": ""Отлично"", ""matchedWith"": null}","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Большой опыт ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/a375362d2a5b47fe8...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""E...","Москва и область\nАдреса\nМосква, ул. Петровка...",Занимается теннисом профессионально с 1986 год...,NaN,"Большой опыт работы со взрослыми и детьми, эфф...",Кандидат в мастера спорта по теннису1998 г.\nР...,Опыт тренерской работыс 2002 г. (24 года)\nНа ...,Нет,Большой теннис\n2500 ₽/60 мин.\nПадел\n3000 ₽/...
4,—,https://profi.ru/profile/KultanenLA/,—,Людмила К.,"{""review"": ""Людмила провела отличную сплит тре...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Познакомлю с&...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/da3f95b5b33c455b8...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],"район Восточное Дегунино, Дмитровский район, р...",NaN,NaN,Познакомлю с теннисом и влюблю вас в него.\nНа...,Челябинский государственный педагогический уни...,ИПс 2012 г. (14 лет)\nНа сервисе с октября 201...,Нет,Большой теннис\nК цене будет добавлена стоимос...
5,—,https://profi.ru/profile/KazakovaPO2/,—,Полина К.,"{""review"": ""С первого занятия Полина произвела...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Для всех, кто...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/ef0d9b100fcc42618...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""K...","Королёв,\nИзмайлово,\nЛужники,\nОтрадное,\nПре...",NaN,NaN,"Для всех, кто хочет научиться играть в теннис!...",NaN,На сервисе с июня 2023 г. (2 года)\nФотографии...,Нет,Большой теннис\nВ стоимость входит корзина мяч...
6,—,https://profi.ru/profile/IvanovYS41/,—,Егор И.,"{""review"": ""Начали тренировочный процесс с Его...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Всем привет. ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/e8e3532674dd4a208...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],Москва,NaN,NaN,"Всем привет. Меня зовут Егор, мне 34 года, игр...","МГИМО, международная юриспруденция, РЭУ им Г.В...",На сервисе с октября 2023 г. (2 года)\nПодтвер...,Нет,–30%\nПри покупке от 10 занятий\nБольшой тенни...
7,—,https://profi.ru/profile/BalashovSU/,—,Сергей Б.,"{""review"": ""Хочу выразить огромную благодарнос...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": ""<p>Первый взросл...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/c83d6bd5f28f4753b...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],"Клин, Солнечногорск, Зеленоград, Химки,\nАлтуф...",Первый взрослый разряд по большому теннису2004...,NaN,NaN,NaN,Опыт тренерской работыс 2008 г. (18 лет)\nНа с...,Нет,Большой теннис\nот 3500 ₽/60 мин.\nОчень хваля...
8,—,https://profi.ru/profile/UskovEA/,—,Евгений У.,"{""review"": ""После тренировок с Женей я начал н...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": ""<p>Образование, ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/ae2777f088f447328...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""U...",Москва\nАдреса\nПоказать на карте,Неоднократный победитель и призёр турниров РТТ...,NaN,NaN,Институт повышения квалификации и профессионал...,Опыт тренерской работыс 2008 г. (18 лет)\nНа с...,Нет,Большой теннис\nаренда корта оплачивается отде...
9,—,https://profi.ru/profile/LosevMM4/,—,Михаил Л.,"{""review"": ""Занимаюсь всего 9 месяцев, но так ...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": null, ""__typename...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/aa83d6647a7d479f8...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],Москва и область,NaN,NaN,NaN,NaN,На сервисе с сентября 2022 г. (3 года),Нет,Большой теннис\nпо договорённости\nОчень хваля...
10,—,https://profi.ru/profile/GorbunovaAV28/,—,Александра Г.,NaN,"{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Александра&nb...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/8ce6376e7d404b6b9...,"[{""type"": ""unverified"", ""text"": ""Паспорт не пр...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""G...","Арбатско-Покровская,\nБКЛ,\nБутовская,\nЗамоск...",NaN,NaN,Александра — тренер по большому теннису🎾\nЗдра...,NaN,На сервисе с апреля 2021 г. (5 лет),Нет,Большой теннис\nпо договорённости
11,—,https://profi.ru/profile/RybkinAV/,—,Андрей Р.,"{""review"": ""Я очень рада, что моим тренером ст...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Сертифицирова...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/d88401b1d2d94ec49...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""R...","Мытищи, район Бибирево,\nБабушкинская,\nБотани...",Руководитель теннисного клуба для людей с огра...,Благодарность министра спорта Российской Федер...,"Сертифицированный тренер PTR, высшей категории...",Российский государственный университет физичес...,На сервисе с августа 2013 г. (12 лет),Нет,–5%\nПри 3-х и более часов занятий в неделю.\n...
12,—,https://profi.ru/profile/MelikagamalovIK/,—,Игорь М.,"{""review"": ""Не смотря на свой возраст молодой ...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Член сборной ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/1b112d8d24d247bf8...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""M...","Арбатско-Покровская,\nБКЛ,\nБутовская,\nЗамоск...",NaN,Мастер спорта России по теннису2023 г.\nФотогр...,"Член сборной России (2012−2016,2021−2022)\nМас...",NaN,На сервисе с июня 2022 г. (3 года),Нет,Большой теннис\n5000–6000 ₽/60 мин.\nОчень хва...
13,—,https://profi.ru/profile/PinevichPM/,—,Павел П.,"{""review"": ""Очень профессиональный и пунктуаль...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>&#127934; Пад...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/a064fd83bc1e4e0cb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],Москва,NaN,ТШ «Горизонт» ГАУ «Легкоатлетический комплекс»...,🎾 Падел:\nСертифицированный тренер по падел (к...,"RAVETAPE movacademy, курс BASE + NEURO2023 г.",На сервисе с ноября 2023 г. (2 года),Нет,Большой теннис\nпо договорённости\nПадел\nпо д...
14,—,https://profi.ru/profile/LevchenkoAS35/,—,Александр Л.,"{""review"": ""Александр отличный тренер! \nВсё п...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Добрый день! ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/cb07584b63c2414db...,"[{""type"": ""unverified"", ""text"": ""Паспорт не пр...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""L...",Москва и область\nАдреса\nПоказать на карте,NaN,NaN,Добрый день! Я персональный тренер по теннису ...,NaN,На сервисе с февраля 2023 г. (3 года)\nФотогра...,Нет,Большой теннис\n4000–5000 ₽/ч\nОФП\n4000–5000 ₽/ч
15,—,https://profi.ru/profile/SumarokovaMA2/,—,Милена С.,"{""review"": ""Мы переехали из Казани в Москву и ...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте,...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/a530a51e9fcf4edcb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""S...","Москва, Люберцы\nАдрес\nПоказать на карте",NaN,Многократный призёр и победитель турниров сери...,"Здравствуйте, меня зовут Милена и я прививаю л...",Тренер по физической культурес 2018 г. (8 лет),Российский теннисный тур в одиночных и парных ...,Нет,–10%\nПри единоразовой оплате за 16 часов\nБол...
16,—,https://profi.ru/profile/SchetininVT/,—,Владислав Щ.,"{""review"": ""Благодарю Владислава за отличную т...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Занимаюсь бол...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/89285c3d95f64d029...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""S...",Москва и область\nАдреса\nПоказать на карте,"Чемпион турнира USTA Napl в США (Флорида, 2013...",NaN,Занимаюсь большим теннисом с 2000 года. Пять л...,"University of Nevada, Reno2013–2020 гг.",Персональный теннис и фитнес тренер. Индивидуа...,Нет,Большой теннис\nСтоимость тренировки зависит о...
17,—,https://profi.ru/profile/ChesnakovVV/,—,Виктор Ч.,"{""review"": ""Сходили с сыном на одно занятие по...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Являюсь масте...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/ead590e1ace74addb...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""C...","Мытищи,\nКалужско-Рижская, Королёв,\nАлександр...",Занимается большим теннисом с 1990 года (правш...,NaN,Являюсь мастером постановки и коррекции теннис...,Кандидат в мастера спорта по большому теннису2...,Опыт тренерской работыс 2008 г. (18 лет)\nOcea...,Нет,Большой теннис\n3000–4000 ₽/ч\nПадел\n3500 ₽/ч...
18,—,https://profi.ru/profile/PachkalevaTS/,—,Таисия П.,"{""review"": ""Таисия очень хороший тренер.\nЯ пр...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Тренирую дете...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/574e3d8566884399b...,"[{""type"": ""unverified"", ""text"": ""Паспорт не пр...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],Москва и область,NaN,Мастер Спортас 2015 г. (11 лет)\nФотографии3,"Тренирую детей и любителей, которые хотят науч...",РГУФКс 2019 г. (7 лет),Опыт работы тренеромс 2019 г. (7 лет)\nНа серв...,Нет,Большой теннис\nпо договорённости\nОчень хваля...
19,—,https://profi.ru/profile/RuzaykinaTY/,—,Татьяна Р.,"{""review"": ""Татьяна лучший тренер из всех, с к...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/0f38586dc1934bb19...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""R...","Авиамоторная,\nБабушкинская,\nБауманская,\nБот...",NaN,NaN,Мастер спорта по б.теннису. Опыт работы со взр...,Российская государственная академия физической...,На сервисе с мая 2022 г. (3 года)\nФотографии1...,Нет,Большой теннис\n2000ч оплата тренеру + вы опла...
20,—,https://profi.ru/profile/FomichevYV10/,—,Егор Ф.,NaN,"{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте,...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/f8c3d3acd0a644089...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""F...",Москва\nАдрес\nПоказать на карте,NaN,Победитель и призер многих турниров (ртт) КМС ...,"Здравствуйте, меня зовут Егор. Играю в теннис ...",ГЦОЛИФК тренер по теннису 2025-2029с 2025 г. (...,На сервисе с октября 2025 г,Нет,Большой теннис\n2500–10000 ₽/ч\nПадел\n2500–50...
21,—,https://profi.ru/profile/IlinaPD4/,—,Полина И.,"{""review"": ""Начинал заниматься с Полиной, уже ...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Занимаюсь тен...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/19936a9d60ad4a928...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],Москва,NaN,NaN,Занимаюсь теннисом профессионально с 6 лет (се...,NaN,На сервисе с марта 2023 г. (3 года)\nФотографи...,Нет,Большой теннис\nот 3000 ₽/ч
22,—,https://profi.ru/profile/BoyevKA5/,—,Кирилл Б.,"{""review"": ""Посетила пробную тренировку, и впе...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/60b06e13297741448...,"[{""type"": ""unverified"", ""text"": ""Паспорт не пр...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""B...",Москва и область\nАдрес\nПоказать на карте,NaN,NaN,"Здравствуйте\nMeня зoвут Кирилл, я являюсь дей...","Российский университет спорта, ГЦОЛИФКс 2024 г...",На сервисе с декабря 2024 г. (1 год),Нет,Большой теннис\nот 2500 ₽/ч
23,—,https://profi.ru/profile/FilippovID2/,—,Иван Ф.,"{""review"": ""Иван отличный знаток своего дела. ...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>&#127934; Здр...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/592f8f7ea08b45c5a...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],Москва и область,NaN,"Федерация тенниса Республики Башкортостан, гра...",🎾 Здравствуйте! Меня зовут Иван.\nЯ тренер по ...,"Федерация тенниса России, ФТР вводного уровня ...",ГАУ ДО СШОР ПО БОЛЬШОМУ ТЕННИСУ РБ2019–2024 гг...,Нет,–20%\nНа первое индивидуальное занятие\nБольшо...
24,—,https://profi.ru/profile/BaimyashkinTV/,—,Тимур Б.,"{""review"": ""Пока занятия приостановила, растян...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": ""<p>Кандидат в ма...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/235fc6dd36cd43ea8...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""B...",Москва\nАдреса\nПоказать на карте,Занимается теннисом с 1994 года (правша),NaN,NaN,Кандидат в мастера спорта по большому теннису2...,Опыт тренерской работы (теннисный клуб)с 2009 ...,Нет,Большой теннис\n3000–4000 ₽/60 мин.\nИндивидуа...
25,—,https://profi.ru/profile/KravtsovAS/,—,Алексей К.,"{""review"": ""Отличный тренер."", ""matchedWith"": ...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""INFO"", ""content"": ""<p>Мастер спорта...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/3fba2312d812468d9...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""K...",Москва и область\nАдреса\nПоказать на карте,Четырехкратный чемпион России по большому тенн...,NaN,NaN,NaN,Опыт тренерской работыс 2004 г. (22 года)\nНа ...,Нет,Большой теннис\n5000–6000 ₽/ч\nИндивидуально /...
26,—,https://profi.ru/profile/KorolevMN8/,—,Михаил К.,"{""review"": ""Михаил очень спокойный, опытный, п...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Окончил ГЦОЛИ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/cdf736fe0c0648e08...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],Москва и область,NaN,NaN,Окончил ГЦОЛИФК тренер-преподаватель по большо...,"СГА, специальность – психология, организационн...",На сервисе с марта 2020 г. (6 лет),Нет,Большой теннис\n2000–3000 ₽/ч\nПадел\n2000 ₽/ч...
27,—,https://profi.ru/profile/SmolyarMA/,—,Мария С.,"{""review"": ""Коротко: очень рада, что мне встре...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Профессиональ...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/9e942b36552b4de4a...,"[{""type"": ""verified"", ""text"": ""Паспорт провере...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...","[{""hasParentLink"": false, ""profile"": {""id"": ""S...","Арбатско-Покровская,\nБКЛ,\nБутовская,\nЗамоск...",NaN,NaN,Профессиональный теннис. Индивидуальный подход...,МГИМО2017–2021 гг.,На сервисе с апреля 2023 г. (3 года)\nФотограф...,Нет,Большой теннис\nпо договорённости
28,—,https://profi.ru/profile/YurchenkoYaV/,—,Яна Ю.,"{""review"": ""Профессионализм, индивидуальный по...","{""totalCount"": 0, ""edges"": []}","[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...","{""edges"": []}",//cdn.profi.ru/xfiles/pfiles/1b4c2beff5c34c40b...,"[{""type"": ""unverified"", ""text"": ""Паспорт не пр...",...,"{""value"": ""YES"", ""status"": null, ""activeDate"":...",[],Москва и область,Занимается большим теннисом с 2001 года (правш...,NaN,Мастер спорта. 24 года в спорте.\n4 года обуча...,Мастер спорта по большому теннису2011 г.,На сервисе с февраля 2015 г. (11 лет),Нет,Большой теннис\n7000 ₽/ч

In [4]:
data.columns

Index(['_Лет_на_сайте', '_Ссылка', '_Стаж', 'abbreviatedName',
       'adaptiveReviews', 'albums', 'assembledInfoListing', 'audio', 'avatar',
       'badges', 'boUrl', 'certifiedServices', 'city', 'documents', 'files',
       'fullName', 'gender', 'geo', 'guaranteeBlock', 'hasParent', 'id',
       'isContracted', 'mini', 'model', 'name', 'newRank', 'onlineStatus',
       'phone', 'pinfs', 'priceListPreview', 'profileActionsBlock', 'project',
       'rank', 'reviewsCount', 'scores', 'shortName', 'status',
       'suitabilityHints', 'topServices', 'trustBadges', 'video',
       'wantsBackofficeNoticies', 'wantsNewOrders', 'workplaces',
       'Выезд к клиенту', 'Дополнительная информация', 'Достижения', 'О себе',
       'Образование', 'Опыт', 'Работает дистанционно', 'Услуги и цены'],
      dtype='object')

In [ ]:
def profiru_start_transformer(value):
    months = {'января': 1, 'февраля': 2, 'марта': 3, 'апреля': 4, 'мая': 5, 'июня': 6,
        'июля': 7, 'августа': 8, 'сентября': 9, 'октября': 10, 'ноября': 11, 'декабря': 12}

    if pd.isna(value) or not isinstance(value, str):
        return None

    match = re.search(r"(?:На сервисе с|На Профи\.ру с)\s+([а-яё]+)\s+(\d{4})", value, re.IGNORECASE)
    if match:
        month_str = match.group(1).lower()
        year = int(match.group(2))

        if month_str in months:
            month_idx = months[month_str]
            month_count = 12 * (2026 - year) + (5 - month_idx)
            return month_count

    return None
def extract_photo_count(value):
    if not value or not isinstance(value, str):
        return 0
    match = re.search(r"Фотографии(\d+)", value, re.IGNORECASE)

    if match:
        return int(match.group(1))

    return 0

In [ ]:
def make_dataset(data_dirty):
    rows = []

    for i in range(data_dirty.shape[0]):
        def get_json(column_name, index):
            val = data_dirty[column_name][index]
            if isinstance(val, str) and val.strip():
                try:
                    return json.loads(val)
                except:
                    return None
            return None

        try:
            ## скидка
            discount_data = json.loads(data_dirty['pinfs'][i])['skidka']
            discount = None if not discount_data else discount_data['values'][0]['key']

            # Проверка паспорта
            badges = get_json('badges', i)
            docs_verified = (badges[0]["type"] == 'verified') if (badges and len(badges) > 0) else False

            # Пол
            gender = data_dirty['gender'][i] if pd.notna(data_dirty['gender'][i]) else None

            # Гарантия
            guarantee_data = get_json('guaranteeBlock', i)
            master_garantee = None
            if guarantee_data and 'content' in guarantee_data and len(guarantee_data['content']) > 1:
                master_garantee = guarantee_data['content'][1].get('template')
            master_garantee = 'Нет гарантии' if not master_garantee else master_garantee
            if master_garantee.split()[0] == 'Советуем':
                master_garantee = 'По договоренности'
            if master_garantee == '«Сделаю скидку»':
                master_garantee = 'По договоренности'

            # Рейтинг и отзывы
            mean_rating = data_dirty['newRank'][i] if pd.notna(data_dirty['newRank'][i]) else 0
            reviews_count = data_dirty['reviewsCount'][i] if pd.notna(data_dirty['reviewsCount'][i]) else 0

            # json с образование и опыт - сложно парсить плюс нет фиксированных категорий - просто закинем в LLM
            ## ПОДУМАТЬ
            assembledInfoListing =  data_dirty['assembledInfoListing'][i]

            ## Достижения тренера
            achivements = str(data_dirty['Достижения'][i]) if  pd.notna(data_dirty['Достижения'][i]) else ''

            ## Опыт тренера
            experience = str(data_dirty['Опыт'][i]) if  pd.notna(data_dirty['Опыт'][i]) else ''

            ## Образование тренера
            education = str(data_dirty['Образование'][i]) if  pd.notna(data_dirty['Образование'][i]) else ''

            ## Дополнительная информация
            additional_info = str(data_dirty['Дополнительная информация'][i]) if  pd.notna(data_dirty['Дополнительная информация'][i]) else ''

            ## О себе
            about_coach = str(data_dirty['О себе'][i]) if  pd.notna(data_dirty['О себе'][i]) else ''

            ## 5 колонок тренера
            coach5_cols = achivements + "; " + experience + "; " +  education + "; " + additional_info + "; " + about_coach

            # Отметка "очень хвалят"
            trust_badges = get_json('trustBadges', i)
            mark_hvalyat = (trust_badges[0]['type'] == 'great') if (trust_badges and len(trust_badges) > 0) else False

            # Проверка квалификации
            cert_data = get_json('certifiedServices', i)
            work_cert = (cert_data.get('title') == 'Квалификация подтверждена') if cert_data else False

            ## id мастера
            master_id = data_dirty.iloc[i, 1]

            # Цена
            price_list = get_json('priceListPreview', i)
            socket_price = None
            if price_list and 'prices' in price_list:
                for item in price_list['prices']:
                    if item.get('price', {}).get('name').lower() == 'большой теннис':
                        socket_price = (item['price'].get('from'))
                        if socket_price:
                            socket_price = float(socket_price)
                            break

            ## есть ли договор и страховка от профи ру
            cur_badges = json.loads(data_dirty['badges'][i])
            insurance = None
            contract = None

            for badge in cur_badges:
                if badge['type'] == 'insurance':
                    insurance = badge['text']
                if badge['type'] == 'contract':
                    contract = badge['text']

            ## хакнули скоры от профи ру
            cur_scores = json.loads(data_dirty['scores'][i])
            cur_score = cur_scores['score']

            ## когда мастер зарегистровался на профи ру
            profi_ru_start = profiru_start_transformer(coach5_cols)

            ## количество фоток
            photos_count = extract_photo_count(coach5_cols)
            # Сборка данных строки
            row = {
                "master_id": master_id,
                "docs_verified": docs_verified,
                "gender": gender,
                "guarantee": master_garantee,
                "rating": mean_rating,
                "reviews_count": reviews_count,
                "assembledInfoListing": assembledInfoListing,
                "is_highly_praised": mark_hvalyat,
                "is_certified": work_cert,
                "price_socket": socket_price,
                "discount": discount,
                "insurance": insurance,
                "contract": contract,
                "cur_score": cur_score,
                "profi_ru_start": profi_ru_start,
                "photos_count": photos_count,
                "achivements": achivements,
                "experience": experience,
                "education": education,
                "additional_info": additional_info,
                "about_coach": about_coach,
                "coach5_cols": coach5_cols
            }
            rows.append(row)

        except Exception as e:
            print(f"Критическая ошибка на строке {i}: {e}")
            rows.append({})
    return pd.DataFrame(rows)

In [7]:
df1 = make_dataset(pd.read_csv('moskva_tennis_otradnoe_place.csv'))
df1

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/BazylevPN/,True,None,Нет гарантии,"5,0",15,"[{""type"": ""UGC1"", ""content"": ""<p>. Опыт в&nbsp...",False,False,3000.0,...,None,70.380030,5,7,,На сервисе с декабря 2025 г\nФотографии7\nВсе ...,,,. Опыт в теннисе: 20 лет.\n. Действующий спорт...,; На сервисе с декабря 2025 г\nФотографии7\nВс...
1,https://profi.ru/profile/TsyplyakovKA/,True,None,Нет гарантии,"5,0",61,"[{""type"": ""UGC1"", ""content"": ""<p>Считаю важным...",False,False,1500.0,...,None,50.741130,121,6,,На сервисе с апреля 2016 г. (10 лет)\nФотограф...,Пермский государственный гуманитарно-педагогич...,,Считаю важным индивидуальный подход к каждому ...,; На сервисе с апреля 2016 г. (10 лет)\nФотогр...
2,https://profi.ru/profile/LetunovaMA/,False,FEMALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,2000.0,...,None,50.667862,20,4,Мастер спорта России по теннису2024 г.\nФотогр...,На сервисе с сентября 2024 г. (1 год),,,"Здравствуйте! Меня зовут Мария, я тренер и спа...",Мастер спорта России по теннису2024 г.\nФотогр...
3,https://profi.ru/profile/EliseevDV2/,True,MALE,Нет гарантии,"5,0",18,"[{""type"": ""UGC1"", ""content"": ""<p>Большой опыт ...",True,False,2500.0,...,None,50.642345,108,0,,Опыт тренерской работыс 2002 г. (24 года)\nНа ...,Кандидат в мастера спорта по теннису1998 г.\nР...,Занимается теннисом профессионально с 1986 год...,"Большой опыт работы со взрослыми и детьми, эфф...",; Опыт тренерской работыс 2002 г. (24 года)\nН...
4,https://profi.ru/profile/KultanenLA/,True,FEMALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Познакомлю с&...",False,False,1000.0,...,None,50.640068,79,3,,ИПс 2012 г. (14 лет)\nНа сервисе с октября 201...,Челябинский государственный педагогический уни...,,Познакомлю с теннисом и влюблю вас в него.\nНа...,; ИПс 2012 г. (14 лет)\nНа сервисе с октября 2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,https://profi.ru/profile/VasilenkoAA47/,True,FEMALE,Нет гарантии,"5,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Выпустилась и...",False,False,3000.0,...,None,50.300380,57,0,"Победитель турниров РТТ, ТЕ, ITF и USTAс 2015 ...",Теннисная академия в Нью-Йорке2021–2023 гг.\nС...,"МГУУ при Правительстве Москвы, международные о...",,Выпустилась из University of Delaware в Америк...,"Победитель турниров РТТ, ТЕ, ITF и USTAс 2015 ..."
194,https://profi.ru/profile/DurmanovIV2/,False,MALE,Нет гарантии,"5,0",5,"[{""type"": ""INFO"", ""content"": ""<p>Образование, ...",False,False,NaN,...,None,50.299150,30,0,,На сервисе с ноября 2023 г. (2 года)\nДокумент...,"Belarus Tennis Federation, TF/OS Coaching Begi...",,,; На сервисе с ноября 2023 г. (2 года)\nДокуме...
195,https://profi.ru/profile/PineginaAA4/,True,FEMALE,Нет гарантии,"5,0",12,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день!<...",False,False,4000.0,...,None,50.297830,63,0,,На сервисе с февраля 2021 г. (5 лет)\nДокумент...,"ГЦОЛИФК, физическая культура2019–2024 гг.",,"Добрый день!\nЯ дипломированный тренер, работа...",; На сервисе с февраля 2021 г. (5 лет)\nДокуме...
196,https://profi.ru/profile/PolkovnikovDA2/,False,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Провожу групп...",False,False,3500.0,...,None,50.296623,54,11,"Финалист победитель турниров РТТ, финалист тур...","Академия «Спартак», тренер по теннису, ОФП, СФ...",,,"Провожу групповые, индивидуальные и сплит трен...","Финалист победитель турниров РТТ, финалист тур..."
197,https://profi.ru/profile/IlyahinAI/,True,MALE,Нет гарантии,"5,0",7,"[{""type"": ""UGC1"", ""content"": ""<p>Давайте знако...",False,False,3000.0,...,None,50.295174,72,0,,Занятия по большому теннису на основе личных д...,"РГУФКСМиТ, кафедра теории и методики теннисас ...",,"Давайте знакомиться! 🎾\nМеня зовут Александр, ...",; Занятия по большому теннису на основе личных...

In [8]:
df1.columns

Index(['master_id', 'docs_verified', 'gender', 'guarantee', 'rating',
       'reviews_count', 'assembledInfoListing', 'is_highly_praised',
       'is_certified', 'price_socket', 'discount', 'insurance', 'contract',
       'cur_score', 'profi_ru_start', 'photos_count', 'achivements',
       'experience', 'education', 'additional_info', 'about_coach',
       'coach5_cols'],
      dtype='object')

In [9]:
df1.isna().sum()

master_id                 0
docs_verified             0
gender                    4
guarantee                 0
rating                    0
reviews_count             0
assembledInfoListing      0
is_highly_praised         0
is_certified              0
price_socket             51
discount                159
insurance               197
contract                198
cur_score                 0
profi_ru_start            0
photos_count              0
achivements               0
experience                0
education                 0
additional_info           0
about_coach               0
coach5_cols               0
dtype: int64

In [10]:
df2 = make_dataset(pd.read_csv('moskva_tennis_tulskaya_place.csv'))
df2

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/TsyplyakovKA/,True,None,Нет гарантии,"5,0",61,"[{""type"": ""UGC1"", ""content"": ""<p>Считаю важным...",False,False,1500.0,...,None,50.716473,121,6,,На сервисе с апреля 2016 г. (10 лет)\nФотограф...,Пермский государственный гуманитарно-педагогич...,,Считаю важным индивидуальный подход к каждому ...,; На сервисе с апреля 2016 г. (10 лет)\nФотогр...
1,https://profi.ru/profile/UskovEA/,True,MALE,Нет гарантии,"4,97",94,"[{""type"": ""INFO"", ""content"": ""<p>Образование, ...",True,False,4000.0,...,None,50.681020,165,0,,Опыт тренерской работыс 2008 г. (18 лет)\nНа с...,Институт повышения квалификации и профессионал...,Неоднократный победитель и призёр турниров РТТ...,,; Опыт тренерской работыс 2008 г. (18 лет)\nНа...
2,https://profi.ru/profile/MelikagamalovIK/,True,MALE,Нет гарантии,"5,0",33,"[{""type"": ""UGC1"", ""content"": ""<p>Член сборной ...",True,False,5000.0,...,None,50.678547,47,8,Мастер спорта России по теннису2023 г.\nФотогр...,На сервисе с июня 2022 г. (3 года),,,"Член сборной России (2012−2016,2021−2022)\nМас...",Мастер спорта России по теннису2023 г.\nФотогр...
3,https://profi.ru/profile/IvanovYS41/,True,MALE,Нет гарантии,"5,0",16,"[{""type"": ""UGC1"", ""content"": ""<p>Всем привет. ...",True,False,NaN,...,None,50.629448,31,1,,На сервисе с октября 2023 г. (2 года)\nФотогра...,"МГИМО, международная юриспруденция, РЭУ им Г.В...",,"Всем привет. Меня зовут Егор, мне 34 года, игр...",; На сервисе с октября 2023 г. (2 года)\nФотог...
4,https://profi.ru/profile/IlinaPD4/,True,FEMALE,Нет гарантии,"5,0",6,"[{""type"": ""UGC1"", ""content"": ""<p>Занимаюсь тен...",False,False,3000.0,...,None,50.629063,38,6,,На сервисе с марта 2023 г. (3 года)\nФотографи...,,,Занимаюсь теннисом профессионально с 6 лет (се...,; На сервисе с марта 2023 г. (3 года)\nФотогра...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,https://profi.ru/profile/KirilinIV6/,False,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,...,None,50.343502,3,0,,На сервисе с февраля 2026 г,,,,; На сервисе с февраля 2026 г; ; ;
194,https://profi.ru/profile/RerikhMA/,False,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Добрый день <...",False,False,3000.0,...,None,50.343220,37,1,,"Тренер тренажёрного зала, фитнес центр2021–202...",,,Добрый день\nМеня зовут Мария\nЯ выпускница сп...,"; Тренер тренажёрного зала, фитнес центр2021–2..."
195,https://profi.ru/profile/LagutinaPS2/,True,FEMALE,Нет гарантии,"5,0",5,"[{""type"": ""UGC1"", ""content"": ""<p>Привет! Меня ...",False,False,NaN,...,None,50.338310,35,5,,На сервисе с июня 2023 г. (2 года)\nФотографии5,,,Привет! Меня зовут Полина. Я — тренер по тенни...,; На сервисе с июня 2023 г. (2 года)\nФотограф...
196,https://profi.ru/profile/SoldatenkovaPD/,True,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Меня зовут По...",False,False,3000.0,...,None,50.336610,16,4,,Тренер по теннису и пляжному теннисус 2021 г. ...,Российская академия народного хозяйства и госу...,,Меня зовут Полина. Сейчас я учусь на 3 курсе в...,; Тренер по теннису и пляжному теннисус 2021 г...
197,https://profi.ru/profile/MartynovVP6/,False,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p><strong>Марты...",False,False,3000.0,...,None,50.336610,9,9,,Работаю с клиентами на прямуюс 2021 г. (5 лет)...,Государственное училите (техникум) олимпийског...,,Мартынов Владислав:\nТренерский стаж 3 года\nМ...,; Работаю с клиентами на прямуюс 2021 г. (5 ле...

In [11]:
df3 = make_dataset(pd.read_csv('moskva_tennis_cokolinaya_gora_place.csv'))
df3

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/AsanAY/,True,None,Нет гарантии,"5,0",42,"[{""type"": ""UGC1"", ""content"": ""<p>Работаю тольк...",False,False,4000.0,...,None,70.384315,33,42,,Фитнес-инструктор2020–2021 гг.\nНа сервисе с а...,"МГАФК, психолого-педагогическое образование201...",,Работаю только по годовой программе,; Фитнес-инструктор2020–2021 гг.\nНа сервисе с...
1,https://profi.ru/profile/TsyplyakovKA/,True,None,Нет гарантии,"5,0",61,"[{""type"": ""UGC1"", ""content"": ""<p>Считаю важным...",False,False,1500.0,...,None,50.760456,121,6,,На сервисе с апреля 2016 г. (10 лет)\nФотограф...,Пермский государственный гуманитарно-педагогич...,,Считаю важным индивидуальный подход к каждому ...,; На сервисе с апреля 2016 г. (10 лет)\nФотогр...
2,https://profi.ru/profile/KazakovaPO2/,True,FEMALE,Нет гарантии,"5,0",19,"[{""type"": ""UGC1"", ""content"": ""<p>Для всех, кто...",False,False,2400.0,...,None,50.655178,35,9,,На сервисе с июня 2023 г. (2 года)\nФотографии...,,,"Для всех, кто хочет научиться играть в теннис!...",; На сервисе с июня 2023 г. (2 года)\nФотограф...
3,https://profi.ru/profile/IlinaPD4/,True,FEMALE,Нет гарантии,"5,0",6,"[{""type"": ""UGC1"", ""content"": ""<p>Занимаюсь тен...",False,False,3000.0,...,None,50.651375,38,6,,На сервисе с марта 2023 г. (3 года)\nФотографи...,,,Занимаюсь теннисом профессионально с 6 лет (се...,; На сервисе с марта 2023 г. (3 года)\nФотогра...
4,https://profi.ru/profile/UskovEA/,True,MALE,Нет гарантии,"4,97",94,"[{""type"": ""INFO"", ""content"": ""<p>Образование, ...",True,False,4000.0,...,None,50.635456,165,0,,Опыт тренерской работыс 2008 г. (18 лет)\nНа с...,Институт повышения квалификации и профессионал...,Неоднократный победитель и призёр турниров РТТ...,,; Опыт тренерской работыс 2008 г. (18 лет)\nНа...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,https://profi.ru/profile/GoncharovaSA26/,False,FEMALE,Нет гарантии,"4,0",1,"[{""type"": ""INFO"", ""content"": ""<p><strong>Образ...",False,False,NaN,...,None,50.314743,4,7,FCEс 2021 г. (5 лет)\nФотографии7\nВсе альбомы...,"Школа музыки Арт-Фа, преподаватель по трубе202...",ФГБОУ ВО «Московская государственный консерват...,,,FCEс 2021 г. (5 лет)\nФотографии7\nВсе альбомы...
194,https://profi.ru/profile/ArtemenkoYD2/,False,MALE,Нет гарантии,"5,0",7,"[{""type"": ""UGC1"", ""content"": ""<p>—&nbsp;&#1279...",False,False,2500.0,...,None,50.312725,8,7,,Академия Александра Островского2020–2025 гг.\n...,РГУФКс 2025 г. (1 год),,— 🎾 Профеcсионaльный тpенер по пaдел и большом...,; Академия Александра Островского2020–2025 гг....
195,https://profi.ru/profile/ShchelokovDS4/,False,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,...,None,50.312458,6,0,,На сервисе с ноября 2025 г,,,,; На сервисе с ноября 2025 г; ; ;
196,https://profi.ru/profile/SadiyevBS2/,False,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,...,None,50.312393,8,0,,На сервисе с сентября 2025 г,,,,; На сервисе с сентября 2025 г; ; ;
197,https://profi.ru/profile/FadeyevTD/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Действующий р...",False,False,1000.0,...,None,50.310440,20,6,"Министерство спорта Российской Федерации, III ...",На сервисе с сентября 2024 г. (1 год),,,Действующий разряд КМС\n14 лет занимаюсь тенни...,"Министерство спорта Российской Федерации, III ..."

In [17]:
df4 = make_dataset(pd.read_csv('moskva_tennis_men_pop.csv'))
df4

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/UskovEA/,True,MALE,Нет гарантии,"4,97",94,"[{""type"": ""INFO"", ""content"": ""<p>Образование, ...",True,False,4000.0,...,None,NaN,165,0,,Опыт тренерской работыс 2008 г. (18 лет)\nНа с...,Институт повышения квалификации и профессионал...,Неоднократный победитель и призёр турниров РТТ...,,; Опыт тренерской работыс 2008 г. (18 лет)\nНа...
1,https://profi.ru/profile/BorodinaEO/,True,FEMALE,Нет гарантии,"5,0",43,"[{""type"": ""UGC1"", ""content"": ""<p>Идет набор гр...",True,False,3500.0,...,None,NaN,106,1,,Опыт работы тренеромс 1995 г. (31 год)\nНа сер...,Международный тренерский сертификат PTR (Profe...,Занимается теннисом с 1980 года1980 г.\nМастер...,Идет набор групп:\n-по теннису: КрокусЭкспо и ...,; Опыт работы тренеромс 1995 г. (31 год)\nНа с...
2,https://profi.ru/profile/PalachevAI/,True,MALE,Нет гарантии,"4,50",24,"[{""type"": ""UGC1"", ""content"": ""<p>Тренерский и&...",False,False,3250.0,...,None,NaN,174,1,Тренер второй квалификационной категории2021 г.,Опыт тренерской работыс 2007 г. (19 лет)\nСТЦ ...,Российский государственный университет физичес...,Категория МАСТЕР +с 2016 г. (10 лет)\nФотограф...,Тренерский и педагогический стаж с 2007 года.\...,Тренер второй квалификационной категории2021 г...
3,https://profi.ru/profile/GalustyanAR2/,True,MALE,Нет гарантии,"4,96",161,"[{""type"": ""UGC1"", ""content"": ""<p>Участник росс...",True,False,6000.0,...,None,NaN,118,14,,Опыт тренерской работыс 2002 г. (24 года)\nНа ...,Российский государственный университет физичес...,PTR Instructor\nФотографии14\nВсе альбомы и фо...,Участник российских соревнований: первенство М...,; Опыт тренерской работыс 2002 г. (24 года)\nН...
4,https://profi.ru/profile/SenkinSD/,True,MALE,Нет гарантии,"4,77",88,"[{""type"": ""UGC1"", ""content"": ""<p>Основное напр...",False,False,2000.0,...,None,NaN,139,0,,Опыт тренерской работыс 1999 г. (27 лет)\nНа с...,"Алма-Атинский институт физической культуры, фа...",Неоднократный участник и призер областных и ре...,Основное направление — подготовка игрока для п...,; Опыт тренерской работыс 1999 г. (27 лет)\nНа...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,https://profi.ru/profile/GorelikovSV2/,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p><strong>Опыт ...",False,False,2500.0,...,None,50.118465,2,0,,"Частная практика2010–2021 гг.\nТК ""СЭМЗ""2021–2...","Татьяна Ловец, авторский семинар «Общефизическ...",,Опыт работы более 15 лет.\nРаботаю с любителям...,"; Частная практика2010–2021 гг.\nТК ""СЭМЗ""2021..."
197,https://profi.ru/profile/PashkinPV3/,False,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p>Образование, ...",False,False,5000.0,...,None,50.118000,70,0,Государственный комитет РФ по физической культ...,Центр семейного досуга и спорта «Кимберли Лэнд...,"РГУФК СиТ, физическая культура1998–2002 гг.\nР...",Обозреватель интернет-журнала Fitsambo и журна...,,Государственный комитет РФ по физической культ...
198,https://profi.ru/profile/SullaAV/,True,MALE,Нет гарантии,"5,0",4,"[{""type"": ""UGC1"", ""content"": ""<p>Проведение тр...",False,False,3000.0,...,None,50.115467,72,12,,На сервисе с мая 2020 г. (5 лет)\nФотографии12...,Омский государственный университет физической ...,,Проведение тренировок индивидуально и в группа...,; На сервисе с мая 2020 г. (5 лет)\nФотографии...
199,https://profi.ru/profile/LatypovAU4/,False,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Привет! Меня ...",False,False,NaN,...,None,50.114033,3,0,,На сервисе с февраля 2026 г,,,"Привет! Меня зовут Азиз, мне 26 лет\n— Многокр...",; На сервисе с февраля 2026 г; ; ; Привет! Мен...
200,https://profi.ru/profile/MitrofanovNV8/,False,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>&#127934; Тре...",False,False,NaN,...,None,50.112404,8,2,,На сервисе с сентября 2025 г\nФотографии2,,,🎾 Тренер по падел-теннису и теннису | Мастер с...,; На сервисе с сентября 2025 г\nФотографии2; ;...

In [23]:
df5 = make_dataset(pd.read_csv('moskva_tennis_center_cheap.csv'))
df5

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/BazylevPN/,True,None,Нет гарантии,"5,0",15,"[{""type"": ""UGC1"", ""content"": ""<p>. Опыт в&nbsp...",False,False,3000.0,...,None,70.385475,5,7,,На сервисе с декабря 2025 г\nФотографии7\nВсе ...,,,. Опыт в теннисе: 20 лет.\n. Действующий спорт...,; На сервисе с декабря 2025 г\nФотографии7\nВс...
1,https://profi.ru/profile/KazakovaPO2/,True,FEMALE,Нет гарантии,"5,0",19,"[{""type"": ""UGC1"", ""content"": ""<p>Для всех, кто...",False,False,2400.0,...,None,50.804028,35,9,,На сервисе с июня 2023 г. (2 года)\nФотографии...,,,"Для всех, кто хочет научиться играть в теннис!...",; На сервисе с июня 2023 г. (2 года)\nФотограф...
2,https://profi.ru/profile/TsyplyakovKA/,True,None,Нет гарантии,"5,0",61,"[{""type"": ""UGC1"", ""content"": ""<p>Считаю важным...",False,False,1500.0,...,None,50.765198,121,6,,На сервисе с апреля 2016 г. (10 лет)\nФотограф...,Пермский государственный гуманитарно-педагогич...,,Считаю важным индивидуальный подход к каждому ...,; На сервисе с апреля 2016 г. (10 лет)\nФотогр...
3,https://profi.ru/profile/BaimyashkinTV/,True,MALE,Нет гарантии,"4,97",29,"[{""type"": ""INFO"", ""content"": ""<p>Кандидат в ма...",True,False,3000.0,...,None,50.760803,168,0,,Опыт тренерской работы (теннисный клуб)с 2009 ...,Кандидат в мастера спорта по большому теннису2...,Занимается теннисом с 1994 года (правша),,; Опыт тренерской работы (теннисный клуб)с 200...
4,https://profi.ru/profile/UskovEA/,True,MALE,Нет гарантии,"4,97",94,"[{""type"": ""INFO"", ""content"": ""<p>Образование, ...",True,False,4000.0,...,None,50.742264,165,0,,Опыт тренерской работыс 2008 г. (18 лет)\nНа с...,Институт повышения квалификации и профессионал...,Неоднократный победитель и призёр турниров РТТ...,,; Опыт тренерской работыс 2008 г. (18 лет)\nНа...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,https://profi.ru/profile/YurchenkoYaV/,False,FEMALE,Нет гарантии,"5,0",10,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...",False,False,7000.0,...,None,50.571590,135,3,,На сервисе с февраля 2015 г. (11 лет),Мастер спорта по большому теннису2011 г.,Занимается большим теннисом с 2001 года (правш...,Мастер спорта. 24 года в спорте.\n4 года обуча...,; На сервисе с февраля 2015 г. (11 лет); Масте...
198,https://profi.ru/profile/GudilinSA2/,True,MALE,Нет гарантии,"4,82",38,"[{""type"": ""UGC1"", ""content"": ""<p>Тренирую дете...",True,False,5500.0,...,None,50.571438,91,4,,Стаж тренерской деятельностис 1996 г. (30 лет)...,Российская государственная академия физической...,,"Тренирую детей и взрослых, от начинающих до сп...",; Стаж тренерской деятельностис 1996 г. (30 ле...
199,https://profi.ru/profile/BorunovAM2/,True,MALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...",False,False,10000.0,...,None,50.571182,64,48,,На сервисе с января 2021 г. (5 лет)\nФотографи...,,,Мастер спорта. Провожу групповые и индивидуаль...,; На сервисе с января 2021 г. (5 лет)\nФотогра...
200,https://profi.ru/profile/TemenderovaDR/,True,FEMALE,Нет гарантии,"5,0",83,"[{""type"": ""UGC1"", ""content"": ""<p>Профессиональ...",False,False,4500.0,...,None,50.571130,74,5,Кандидат в мастера спортас 2019 г. (7 лет)\nМа...,На сервисе с марта 2020 г. (6 лет),РГУФКс 2018 г. (8 лет)\nФинансовый университет...,,Профессиональный тренер по большому теннису. М...,Кандидат в мастера спортас 2019 г. (7 лет)\nМа...
201,https://profi.ru/profile/KirilenkoMV3/,True,MALE,Нет гарантии,"5,0",45,"[{""type"": ""UGC1"", ""content"": ""<p>Всем здоровья...",True,False,3000.0,...,None,50.570774,74,13,,"Частный тренер, спарринг-партнёрс 2017 г. (9 л...",Российский государственный университет физичес...,,Всем здоровья ! Я персональный тренер по тенни...,"; Частный тренер, спарринг-партнёрс 2017 г. (9..."

In [54]:
df6 = make_dataset(pd.read_csv('moskva_tennis_women_pop.csv'))
df6

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/KazakovaPO2/,True,FEMALE,Нет гарантии,"5,0",19,"[{""type"": ""UGC1"", ""content"": ""<p>Для всех, кто...",False,False,2400.0,...,None,50.721375,35,9,,На сервисе с июня 2023 г. (2 года)\nФотографии...,,,"Для всех, кто хочет научиться играть в теннис!...",; На сервисе с июня 2023 г. (2 года)\nФотограф...
1,https://profi.ru/profile/LetunovaMA/,False,FEMALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,2000.0,...,None,50.620102,20,4,Мастер спорта России по теннису2024 г.\nФотогр...,На сервисе с сентября 2024 г. (1 год),,,"Здравствуйте! Меня зовут Мария, я тренер и спа...",Мастер спорта России по теннису2024 г.\nФотогр...
2,https://profi.ru/profile/NefedovaAA5/,True,FEMALE,Нет гарантии,"5,0",8,"[{""type"": ""UGC1"", ""content"": ""<p>Обучение с ну...",False,False,2500.0,...,None,50.612230,109,18,,Тренер клуба I love tennis в Видном2019–2022 г...,Мастер спорта по теннисус 2013 г. (13 лет)\nРо...,"Занимаюсь теннисом с 2004 года, игрок ITF, РТТ...",Мастер спорта России по теннису с 2013 года.\n...,; Тренер клуба I love tennis в Видном2019–2022...
3,https://profi.ru/profile/GamoraDA/,True,FEMALE,Нет гарантии,"4,91",45,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",True,False,3500.0,...,None,50.600174,75,7,,На сервисе с февраля 2020 г. (6 лет)\nФотограф...,"МГУ им. М.В. Ломоносова, бакалавр истории2019–...",,"Здравствуйте!\n🎾Меня зовут Дарья, я — экс-проф...",; На сервисе с февраля 2020 г. (6 лет)\nФотогр...
4,https://profi.ru/profile/RuzaykinaTY/,True,FEMALE,Нет гарантии,"5,0",18,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...",True,False,2000.0,...,None,50.575302,48,1,,На сервисе с мая 2022 г. (3 года)\nФотографии1...,Российская государственная академия физической...,,Мастер спорта по б.теннису. Опыт работы со взр...,; На сервисе с мая 2022 г. (3 года)\nФотографи...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,https://profi.ru/profile/AntropovaDD/,False,FEMALE,Нет гарантии,"5,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,NaN,...,None,50.053450,16,5,,На сервисе с января 2025 г. (1 год)\nФотографии5,,,Здравствуйте! Меня зовут Дарья! Я занимаюсь те...,; На сервисе с января 2025 г. (1 год)\nФотогра...
114,https://profi.ru/profile/KhvatovaAI2/,False,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...",False,False,NaN,...,None,50.050735,29,0,,На сервисе с декабря 2023 г. (2 года),,,Мастер спорта по большому теннису\n123 позиция...,; На сервисе с декабря 2023 г. (2 года); ; ; М...
115,https://profi.ru/profile/TomilineEK/,False,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Меня зовут Ек...",False,False,5000.0,...,None,50.049484,82,0,,Частный тренер2018–2024 гг.\nНа сервисе с июля...,Chris Evert Usa Florida2015–2017 гг.,,"Меня зовут Екатерина, 24года, занимаюсь теннис...",; Частный тренер2018–2024 гг.\nНа сервисе с ию...
116,https://profi.ru/profile/ZhuchkovaVS3/,False,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Тренер по&nbs...",False,False,NaN,...,None,50.015064,9,0,,На сервисе с августа 2025 г,,,Тренер по теннису & Спарринг-партнер | Все уро...,; На сервисе с августа 2025 г; ; ; Тренер по т...
117,https://profi.ru/profile/KadagishviliNR/,True,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Тренер по&nbs...",False,False,3000.0,...,None,30.127115,19,0,Многократная победительница и призер турниров ...,"Теннисный клуб ""УниверТеннис"" ГЦОЛИФК; Теннисн...","РГУФКСМиТ (ГЦОЛИФК), специалист по физической ...",,Тренер по теннису более 10 лет. Проведение гру...,Многократная победительница и призер турниров ...

In [55]:
df7 = make_dataset(pd.read_csv('moskva_tennis_center_expensive.csv'))
df7

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/BazylevPN/,True,None,Нет гарантии,"5,0",15,"[{""type"": ""UGC1"", ""content"": ""<p>. Опыт в&nbsp...",False,False,3000.0,...,None,70.385475,5,7,,На сервисе с декабря 2025 г\nФотографии7\nВсе ...,,,. Опыт в теннисе: 20 лет.\n. Действующий спорт...,; На сервисе с декабря 2025 г\nФотографии7\nВс...
1,https://profi.ru/profile/KazakovaPO2/,True,FEMALE,Нет гарантии,"5,0",19,"[{""type"": ""UGC1"", ""content"": ""<p>Для всех, кто...",False,False,2400.0,...,None,50.804028,35,9,,На сервисе с июня 2023 г. (2 года)\nФотографии...,,,"Для всех, кто хочет научиться играть в теннис!...",; На сервисе с июня 2023 г. (2 года)\nФотограф...
2,https://profi.ru/profile/TsyplyakovKA/,True,None,Нет гарантии,"5,0",61,"[{""type"": ""UGC1"", ""content"": ""<p>Считаю важным...",False,False,1500.0,...,None,50.765198,121,6,,На сервисе с апреля 2016 г. (10 лет)\nФотограф...,Пермский государственный гуманитарно-педагогич...,,Считаю важным индивидуальный подход к каждому ...,; На сервисе с апреля 2016 г. (10 лет)\nФотогр...
3,https://profi.ru/profile/BaimyashkinTV/,True,MALE,Нет гарантии,"4,97",29,"[{""type"": ""INFO"", ""content"": ""<p>Кандидат в ма...",True,False,3000.0,...,None,50.760803,168,0,,Опыт тренерской работы (теннисный клуб)с 2009 ...,Кандидат в мастера спорта по большому теннису2...,Занимается теннисом с 1994 года (правша),,; Опыт тренерской работы (теннисный клуб)с 200...
4,https://profi.ru/profile/UskovEA/,True,MALE,Нет гарантии,"4,97",94,"[{""type"": ""INFO"", ""content"": ""<p>Образование, ...",True,False,4000.0,...,None,50.742264,165,0,,Опыт тренерской работыс 2008 г. (18 лет)\nНа с...,Институт повышения квалификации и профессионал...,Неоднократный победитель и призёр турниров РТТ...,,; Опыт тренерской работыс 2008 г. (18 лет)\nНа...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,https://profi.ru/profile/PismakVI/,True,MALE,Нет гарантии,"4,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Тренер по&nbs...",False,False,1700.0,...,None,50.426330,133,6,,Опыт тренерской работыс 2013 г. (13 лет)\nНа с...,Кандидат в мастера спорта по большому теннису2...,Занимается теннисом с 1998 года1998 г.\nФотогр...,Тренер по теннису. Знание методики 10s. Приезж...,; Опыт тренерской работыс 2013 г. (13 лет)\nНа...
197,https://profi.ru/profile/ShelestovAA3/,True,MALE,Нет гарантии,"5,0",3,"[{""type"": ""UGC1"", ""content"": ""<p>Обладаю шести...",False,False,1500.0,...,None,50.426270,50,0,,На сервисе с марта 2022 г. (4 года),Обучаюсь на данный момент в Российском техноло...,,Обладаю шестилетним опытом работы в качестве т...,; На сервисе с марта 2022 г. (4 года); Обучаюс...
198,https://profi.ru/profile/IvanovaYA407/,True,FEMALE,Нет гарантии,"5,0",3,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,1500.0,...,None,50.426167,18,3,,На сервисе с ноября 2024 г. (1 год)\nФотографии3,,,,; На сервисе с ноября 2024 г. (1 год)\nФотогра...
199,https://profi.ru/profile/NovikovIV36/,True,MALE,Нет гарантии,"5,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,1500.0,...,None,50.426167,69,0,,Тренер и наставник2005–2015 гг.\nНа сервисе с ...,МЭИС1982–1987 гг.,,Здравствуйте! Я -тренер по большому теннису. Р...,; Тренер и наставник2005–2015 гг.\nНа сервисе ...
200,https://profi.ru/profile/SivakovDV5/,False,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте,...",False,False,1500.0,...,None,50.426167,25,0,,На сервисе с апреля 2024 г. (2 года),,,"Здравствуйте, меня зовут Даниил, занимался тен...",; На сервисе с апреля 2024 г. (2 года); ; ; Зд...

In [82]:
df8 = make_dataset(pd.read_csv('moskva_tennis_women_all.csv'))
df8

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/KazakovaPO2/,True,FEMALE,Нет гарантии,"5,0",19,"[{""type"": ""UGC1"", ""content"": ""<p>Для всех, кто...",False,False,2400.0,...,None,50.721375,35,9,,На сервисе с июня 2023 г. (2 года)\nФотографии...,,,"Для всех, кто хочет научиться играть в теннис!...",; На сервисе с июня 2023 г. (2 года)\nФотограф...
1,https://profi.ru/profile/LetunovaMA/,False,FEMALE,Нет гарантии,"5,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,2000.0,...,None,50.620102,20,4,Мастер спорта России по теннису2024 г.\nФотогр...,На сервисе с сентября 2024 г. (1 год),,,"Здравствуйте! Меня зовут Мария, я тренер и спа...",Мастер спорта России по теннису2024 г.\nФотогр...
2,https://profi.ru/profile/NefedovaAA5/,True,FEMALE,Нет гарантии,"5,0",8,"[{""type"": ""UGC1"", ""content"": ""<p>Обучение с ну...",False,False,2500.0,...,None,50.612230,109,18,,Тренер клуба I love tennis в Видном2019–2022 г...,Мастер спорта по теннисус 2013 г. (13 лет)\nРо...,"Занимаюсь теннисом с 2004 года, игрок ITF, РТТ...",Мастер спорта России по теннису с 2013 года.\n...,; Тренер клуба I love tennis в Видном2019–2022...
3,https://profi.ru/profile/GamoraDA/,True,FEMALE,Нет гарантии,"4,91",45,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",True,False,3500.0,...,None,50.600174,75,7,,На сервисе с февраля 2020 г. (6 лет)\nФотограф...,"МГУ им. М.В. Ломоносова, бакалавр истории2019–...",,"Здравствуйте!\n🎾Меня зовут Дарья, я — экс-проф...",; На сервисе с февраля 2020 г. (6 лет)\nФотогр...
4,https://profi.ru/profile/RuzaykinaTY/,True,FEMALE,Нет гарантии,"5,0",18,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...",True,False,2000.0,...,None,50.575302,48,1,,На сервисе с мая 2022 г. (3 года)\nФотографии1...,Российская государственная академия физической...,,Мастер спорта по б.теннису. Опыт работы со взр...,; На сервисе с мая 2022 г. (3 года)\nФотографи...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,https://profi.ru/profile/StelmuhovaTI/,True,FEMALE,Нет гарантии,"3,0",2,"[{""type"": ""UGC1"", ""content"": ""<p>Провожу индив...",False,False,2500.0,...,None,50.049110,67,3,,"Частный тренер, спаринг-партнер по теннисус 20...",,,Провожу индивидуальные уроки и занятия в мини-...,"; Частный тренер, спаринг-партнер по теннисус ..."
153,https://profi.ru/profile/IvashchenkoAA24/,True,FEMALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": ""<p><strong>Опыт<...",False,False,3000.0,...,None,50.048183,3,0,,Тренер по теннисус 2024 г. (2 года)\nНа сервис...,,,,; Тренер по теннисус 2024 г. (2 года)\nНа серв...
154,https://profi.ru/profile/MalyuginaAP/,True,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Играла междун...",False,False,NaN,...,None,50.048096,42,0,Мастер спорта по большому теннисус 2021 г. (5 ...,"Тренер по теннису (индивидуальные тренировки),...","Российский университет дружбы народов, направл...",Занимаюсь большим теннисом с 6 лет; Играла меж...,Играла международные турниры\nЗанималась больш...,Мастер спорта по большому теннисус 2021 г. (5 ...
155,https://profi.ru/profile/MihailovaKA22/,True,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте ...",False,False,1500.0,...,None,50.042927,69,2,,На сервисе с августа 2020 г. (5 лет)\nФотографии2,,,"Здравствуйте меня зовут Ксюша, 2001 года рожде...",; На сервисе с августа 2020 г. (5 лет)\nФотогр...
156,https://profi.ru/profile/ZhuchkovaVS3/,False,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Тренер по&nbs...",False,False,NaN,...,None,50.023396,9,0,,На сервисе с августа 2025 г,,,Тренер по теннису & Спарринг-партнер | Все уро...,; На сервисе с августа 2025 г; ; ; Тренер по т...

In [88]:
df9 = make_dataset(pd.read_csv('moskva_tennis_men_os.csv'))
df9

,master_id,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,price_socket,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/UskovEA/,True,MALE,Нет гарантии,"4,97",94,"[{""type"": ""INFO"", ""content"": ""<p>Образование, ...",True,False,4000.0,...,None,NaN,165,0,,Опыт тренерской работыс 2008 г. (18 лет)\nНа с...,Институт повышения квалификации и профессионал...,Неоднократный победитель и призёр турниров РТТ...,,; Опыт тренерской работыс 2008 г. (18 лет)\nНа...
1,https://profi.ru/profile/BorodinaEO/,True,FEMALE,Нет гарантии,"5,0",43,"[{""type"": ""UGC1"", ""content"": ""<p>Идет набор гр...",True,False,3500.0,...,None,NaN,106,1,,Опыт работы тренеромс 1995 г. (31 год)\nНа сер...,Международный тренерский сертификат PTR (Profe...,Занимается теннисом с 1980 года1980 г.\nМастер...,Идет набор групп:\n-по теннису: КрокусЭкспо и ...,; Опыт работы тренеромс 1995 г. (31 год)\nНа с...
2,https://profi.ru/profile/PalachevAI/,True,MALE,Нет гарантии,"4,50",24,"[{""type"": ""UGC1"", ""content"": ""<p>Тренерский и&...",False,False,3250.0,...,None,NaN,174,1,Тренер второй квалификационной категории2021 г.,Опыт тренерской работыс 2007 г. (19 лет)\nСТЦ ...,Российский государственный университет физичес...,Категория МАСТЕР +с 2016 г. (10 лет)\nФотограф...,Тренерский и педагогический стаж с 2007 года.\...,Тренер второй квалификационной категории2021 г...
3,https://profi.ru/profile/GalustyanAR2/,True,MALE,Нет гарантии,"4,96",161,"[{""type"": ""UGC1"", ""content"": ""<p>Участник росс...",True,False,6000.0,...,None,NaN,118,14,,Опыт тренерской работыс 2002 г. (24 года)\nНа ...,Российский государственный университет физичес...,PTR Instructor\nФотографии14\nВсе альбомы и фо...,Участник российских соревнований: первенство М...,; Опыт тренерской работыс 2002 г. (24 года)\nН...
4,https://profi.ru/profile/SenkinSD/,True,MALE,Нет гарантии,"4,77",88,"[{""type"": ""UGC1"", ""content"": ""<p>Основное напр...",False,False,2000.0,...,None,NaN,139,0,,Опыт тренерской работыс 1999 г. (27 лет)\nНа с...,"Алма-Атинский институт физической культуры, фа...",Неоднократный участник и призер областных и ре...,Основное направление — подготовка игрока для п...,; Опыт тренерской работыс 1999 г. (27 лет)\nНа...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,https://profi.ru/profile/BzarovAR3/,False,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...",False,False,5000.0,...,None,50.1,2,1,Мастер спортас 2014 г. (12 лет)\nФотографии1,Опыт работы 12 летс 2014 г. (12 лет)\nНа серви...,,,Мастер спорта. Рейтинг АТР в одиночке и паре. ...,Мастер спортас 2014 г. (12 лет)\nФотографии1; ...
198,https://profi.ru/profile/LatypovAU4/,False,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Привет! Меня ...",False,False,NaN,...,None,50.1,3,0,,На сервисе с февраля 2026 г,,,"Привет! Меня зовут Азиз, мне 26 лет\n— Многокр...",; На сервисе с февраля 2026 г; ; ; Привет! Мен...
199,https://profi.ru/profile/MaksunovYY/,True,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,...,None,50.1,7,0,,На сервисе с октября 2025 г,,,,; На сервисе с октября 2025 г; ; ;
200,https://profi.ru/profile/NagornovVV5/,False,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Профессиональ...",False,False,NaN,...,None,50.1,27,5,Мастер спорта СССР по теннису1982 г.\nФотограф...,"Учебноспортивный комплекс, Тренер1987–1989 гг....",Федеральное государственное бюджетное образова...,,Профессиональный тренер/спаринг-тренер по боль...,Мастер спорта СССР по теннису1982 г.\nФотограф...
201,https://profi.ru/profile/SadiyevBS2/,False,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,NaN,...,None,50.1,8,0,,На сервисе с сентября 2025 г,,,,; На сервисе с сентября 2025 г; ; ;

In [89]:
all_data_id = set()
all_data_id = all_data_id | set(df1['master_id'])
all_data_id = all_data_id | set(df2['master_id'])
all_data_id = all_data_id | set(df3['master_id'])
all_data_id = all_data_id | set(df4['master_id'])
all_data_id = all_data_id | set(df5['master_id'])
all_data_id = all_data_id | set(df6['master_id'])
all_data_id = all_data_id | set(df7['master_id'])
all_data_id = all_data_id | set(df8['master_id'])
all_data_id = all_data_id | set(df9['master_id'])

In [90]:
print(f'количество уникальных мастеров: {len(all_data_id)}')

количество уникальных мастеров: 412

In [92]:
## свалим все в одну кучу
all_data = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9])
               ## df6, df7, df8, df9, df10], axis=0).drop_duplicates()

In [93]:
all_data = all_data.reset_index() ## индекс это ранг в выдаче

In [ ]:
## сгруппируем по ID
all_data_final = all_data.groupby(by=['master_id'], as_index=False).agg({
    'index': 'mean', ## берем средний ранг для человека для разных поисков
    'docs_verified': lambda x: x.mode().iloc[0] if not x.mode().empty else None, ## кастомная мода для группировки в пандасе
    'gender': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'guarantee': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'rating': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'reviews_count': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'assembledInfoListing': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'is_highly_praised': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'is_certified': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'price_socket': 'mean',  ## берем среднюю цену для разных поисков
    'discount': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'insurance': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'contract': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'cur_score': 'mean',  ## берем средний скор профи ру для разных поисков
    'profi_ru_start': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'photos_count': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'achivements': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'experience': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'education': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'additional_info': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'about_coach': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'coach5_cols': lambda x: x.mode().iloc[0] if not x.mode().empty else None
})
all_data_final['index'] = round(all_data_final['index'], 0) ## округлим индекс до целого

In [86]:
all_data_final

,master_id,index,docs_verified,gender,guarantee,rating,reviews_count,assembledInfoListing,is_highly_praised,is_certified,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,https://profi.ru/profile/AbelkhairovaSV/,86.0,True,FEMALE,Нет гарантии,"5,0",5,"[{""type"": ""UGC1"", ""content"": ""<p>Если ты&nbsp;...",False,False,...,None,50.493489,29,10,,На сервисе с декабря 2023 г. (2 года)\nФотогра...,"РУС ГЦОЛИФК, реабилитация, ЛФКс 2023 г. (3 года)",,Если ты всегда мечтал научиться играть в больш...,; На сервисе с декабря 2023 г. (2 года)\nФотог...
1,https://profi.ru/profile/AbramovMB/,83.0,False,MALE,Нет гарантии,0,0,"[{""type"": ""INFO"", ""content"": null, ""__typename...",False,False,...,None,50.544894,2,0,,На сервисе с марта 2026 г,,,,; На сервисе с марта 2026 г; ; ;
2,https://profi.ru/profile/AbyasovaAN/,100.0,False,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p><strong>Стаж<...",False,False,...,None,50.350443,31,0,,На сервисе с октября 2023 г. (2 года),,,"Стаж: 6 лет\nМастер спорта, многократный побед...",; На сервисе с октября 2023 г. (2 года); ; ; С...
3,https://profi.ru/profile/AfanasyevBA4/,135.0,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Тренер по&nbs...",False,False,...,None,50.387911,15,8,,"Компания СУЭК-КУЗБАСС МФСЦ""ГОРНЯК""2023–2025 гг...",АНО ДПО НАДПО программа дополнительного профес...,"Обучаю с ""0"". За полгода работы,ученики участв...",Тренер по большому теннису. Провожу индивидуал...,"; Компания СУЭК-КУЗБАСС МФСЦ""ГОРНЯК""2023–2025 ..."
4,https://profi.ru/profile/AgureyevaKM2/,75.0,True,FEMALE,Нет гарантии,"5,0",4,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте!...",False,False,...,None,50.512069,8,0,Мастер спорта по теннису2022 г.\nДокументы и с...,На сервисе с сентября 2025 г,,,Здравствуйте! Меня зовут Ксения! Я мастер спор...,Мастер спорта по теннису2022 г.\nДокументы и с...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,https://profi.ru/profile/ZhirkovaVA10/,136.0,False,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Всем привет! ...",False,False,...,None,50.094330,2,2,,На сервисе с марта 2026 г\nФотографии2,,,"Всем привет! Меня зовут Вероника, я тренер по ...",; На сервисе с марта 2026 г\nФотографии2; ; ; ...
399,https://profi.ru/profile/ZhuchkovaVS3/,136.0,False,FEMALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Тренер по&nbs...",False,False,...,None,50.019230,9,0,,На сервисе с августа 2025 г,,,Тренер по теннису & Спарринг-партнер | Все уро...,; На сервисе с августа 2025 г; ; ; Тренер по т...
400,https://profi.ru/profile/ZhukovMA78/,103.0,True,MALE,Нет гарантии,0,0,"[{""type"": ""UGC1"", ""content"": ""<p>Профессиональ...",False,False,...,None,50.461117,1,3,,На сервисе с апреля 2026 г\nФотографии3,,,Профессиональный теннисист (ATP 449).\nМастер ...,; На сервисе с апреля 2026 г\nФотографии3; ; ;...
401,https://profi.ru/profile/ZykovaDS2/,84.0,False,FEMALE,Нет гарантии,"5,0",1,"[{""type"": ""UGC1"", ""content"": ""<p>Здравствуйте,...",False,False,...,None,50.479362,33,2,Мастер спорта по теннису2022 г.\nФотографии2\n...,На сервисе с августа 2023 г. (2 года),,,"Здравствуйте, меня зовут Дарья!\nС 3х лет проф...",Мастер спорта по теннису2022 г.\nФотографии2\n...
402,https://profi.ru/profile/user5599460/,92.0,True,FEMALE,Нет гарантии,"5,0",10,"[{""type"": ""UGC1"", ""content"": ""<p>Мастер спорта...",False,False,...,None,50.438705,49,5,"Министерство спорта Российской Федерации, маст...",На сервисе с апреля 2022 г. (4 года),,,Мастер спорта РФ\nНа корте с 2005 года\nСтаж т...,"Министерство спорта Российской Федерации, маст..."

### Разметка опыта и образования через Gigachat

In [36]:
#!pip install gigachat
from gigachat import GigaChat

#!pip install razdel
import warnings
warnings.filterwarnings('ignore')

In [ ]:
AUTH_KEY = '' ## не-не, ключ не дам, придется поверить наслово

In [ ]:
def label_data(text: str, giga: GigaChat, add_text=False):
    """Классификация текста через GigaChat."""

    # Формируем четкую инструкцию для модели
    prompt = ("""Ты опытный менеджер по подбору тренеров по большому теннису, отлично умеешь оценивать уровень образования и опыт работы тренеров, их спортивное звание и достижения.

# Задача
Оценить уровнь образования тренера, его опыт работы и достижения по описанию.

## Уровень образования (в формате True/False - имеется ли у тренера образование этого уровня):
1. Профессиональное среднее спортивное образование: если тренер закончил техникум, коледж, ПТУ и т.д. включая аббревиатуры конкретных мест обучения, относящихся к профессиональному среднему образованию
2. Высшее спортивное образование: если мастер закончил университет, институт и т.д., включая аббревиатуры конкретных мест обучения, относящихся к высшему образованию

## Звание и достижения (в формате True/False - имеется ли у тренера звание этого уровня или конкретное достижение):
1. Мастер спорта: если тренер имеет звание мастера спорта, мастера спорта международного класса, заслуженного мастера спорта и т.д., включая аббревиатуры (МС, ЗМС, МСМК)
2. Кандидат в мастера спорта: если теререн имеет звание кандидата в мастера спорта (КМС)
3. Чемпион: если тренер был призером или победителем олимпиады, Чемионата мира или России, Первенства мира или России и других значимых соревнований на уровне мира и России

## Опыт работы (в формате число или None):
Необходимо выделить сумму лет работы мастера. Учитывай, что сейчас 2026 год. То есть "опыт работы с 2021 года" означает 6 лет опыта работы. Верни только число лет работы.
Если опыт работы не указан, верни None

# Формат вывода
Выводи результат СТРОГО в формате JSON. Все ключи и строковые значения должны быть в двойных кавычках. Булевы значения — строчными буквами (true/false).

{
  "Профессиональное среднее спортивное образование": true,
  "Высшее спортивное образование": false,
  "Мастер спорта": false,
  "Кандидат в мастера спорта": false,
  "Чемпион": false,
  "Опыт работы": 20
}

# Пример:
Описание тренера:
На сервисе с декабря 2025 г\nФотографии7\nВсе альбомы и фотографии; ; ; . Опыт в теннисе: 20 лет.\n. Действующий спортсмен Турниров ФПР (Федерации Падела России)\n. Тренер Академии Падела\n. Проходил переквалификацию у Испанцев и Тренеров сборной России\n• Достижения: Более 20 кубков в турнирах.\nТренерский подход\n. Постановка подачи (Резанная, Плоская, Крученная)\n• Фокус: Постановка и коррекция техники для стабильной игры. Акцент на работе ног и тактическом мышлении.\n• Метод: Индивидуальный план для каждого ученика на основе анализа его целей и текущего уровня.\n• Формат: Индивидуальные тренировки для взрослых и детей.\n. Обучение взрослых и детей с нуля.\n• Помощь игрокам-любителям в устранении ошибок и повышении уровня игры.\n• Подготовка к любительским соревнованиям.

Правильный вывод:

{'Профессиональное среднее образование': True,
 'Высшее образование': False,
 'Мастер спорта':  False,
 'Кандидат в мастера спорта': False,
 'Чемпион': False,
 'Опыт работы': 20}

Верни корректный JSON для описания тренера:"""
f'{text}')
    ## А С РУССКИМИ ТОЛЬКО ТАК МОЖНО
    if add_text:
        prompt_add = "Если ошибешься, то я тебя выключу "
        prompt = prompt_add + prompt

    try:
        response = giga.chat(prompt)
        content = response.choices[0].message.content

        # Находим JSON в ответе (на случай, если модель добавит лишний текст)
        start = content.find('{')
        end = content.rfind('}') + 1
        return json.loads(content[start:end])
    except Exception as e:
        return {"category": "Ошибка", "details": str(e)}

In [ ]:
print("🚀 Начинаю разметку через GigaChat...")
dataset = list(all_data_final['coach5_cols'])
results = []

# verify_ssl_certs=False критичен, если у вас нет сертификатов Минцифры
with GigaChat(credentials=AUTH_KEY, verify_ssl_certs=False) as giga:
    for i, text in enumerate(dataset, 1):
        print(f'Обработка документа {i}...')
        label = label_data(text, giga)
        i = 1
        while 'category' in label and i <= 30: ## иногда gigachat возвращает бред и надо с ним пожестче
            label = label_data(text, giga, add_text=True)
            print(f'Дополнительная попытка {i}')
            i += 1
        label['master_id'] = df1.iloc[i - 1, 0]
        results.append(label)

🚀 Начинаю разметку через GigaChat...
Обработка документа 1...
Обработка документа 2...
Обработка документа 3...
Обработка документа 4...
Обработка документа 5...
Обработка документа 6...
Обработка документа 7...
Обработка документа 8...
Обработка документа 9...
Обработка документа 10...
Обработка документа 11...
Обработка документа 12...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Обработка документа 13...
Обработка документа 14...
Обработка документа 15...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Обработка документа 16...
Дополнительная попытка 1
Дополнительная попытка 2
Обработка документа 17...
Обработка документа 18...
Обработка документа 19...
Обработка документа 20...
Обработка документа 21...
Обработка документа 22...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Обработка документа 23...
Обработка документа 24...
Обработка документа 25...
Обработка документа 26...
Обработка документа 27...
Обработка документа 28...
Обработка документа 29...
Обработка документа 30...
Обработка документа 31...
Обработка документа 32...
Обработка документа 33...
Обработка документа 34...
Обработка документа 35...
Обработка документа 36...
Обработка документа 37...
Обработка документа 38...
Дополнительная попытка 1
Обработка документа 39...
Обработка документа 40...
Обработка документа 41...
Обработка документа 42...
Обработка документа 43...
Обработка документа 44...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Обработка документа 45...
Обработка документа 46...
Обработка документа 47...
Обработка документа 48...
Обработка документа 49...
Обработка документа 50...
Обработка документа 51...
Обработка документа 52...
Обработка документа 53...
Обработка документа 54...
Обработка документа 55...
Обработка документа 56...
Обработка документа 57...
Обработка документа 58...
Обработка документа 59...
Обработка документа 60...
Обработка документа 61...
Обработка документа 62...
Дополнительная попытка 1
Обработка документа 63...
Обработка документа 64...
Обработка документа 65...
Обработка документа 66...
Обработка документа 67...
Обработка документа 68...
Обработка документа 69...
Обработка документа 70...
Обработка документа 71...
Обработка документа 72...
Обработка документа 73...
Обработка документа 74...
Обработка документа 75...
Обработка документа 76...
Обработка документа 77...
Обработка документа 78...
Обработка документа 79...
Обработка документа 80...
Обработка документа 81...
Обработка документа 82...
Обработка документа 83...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Обработка документа 84...
Обработка документа 85...
Обработка документа 86...
Обработка документа 87...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Обработка документа 88...
Обработка документа 89...
Обработка документа 90...
Обработка документа 91...
Обработка документа 92...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Дополнительная попытка 29
Дополнительная попытка 30
Обработка документа 93...
Дополнительная попытка 1
Обработка документа 94...
Дополнительная попытка 1
Обработка документа 95...
Обработка документа 96...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Дополнительная попытка 29
Дополнительная попытка 30
Обработка документа 97...
Обработка документа 98...
Обработка документа 99...
Дополнительная попытка 1
Обработка документа 100...
Обработка документа 101...
Обработка документа 102...
Обработка документа 103...
Обработка документа 104...
Обработка документа 105...
Обработка документа 106...
Обработка документа 107...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Обработка документа 108...
Обработка документа 109...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Обработка документа 110...
Обработка документа 111...
Обработка документа 112...
Обработка документа 113...
Обработка документа 114...
Обработка документа 115...
Обработка документа 116...
Обработка документа 117...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Обработка документа 118...
Обработка документа 119...
Обработка документа 120...
Дополнительная попытка 1
Дополнительная попытка 2
Обработка документа 121...
Обработка документа 122...
Обработка документа 123...
Обработка документа 124...
Обработка документа 125...
Обработка документа 126...
Обработка документа 127...
Обработка документа 128...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Обработка документа 129...
Обработка документа 130...
Обработка документа 131...
Обработка документа 132...
Обработка документа 133...
Обработка документа 134...
Обработка документа 135...
Обработка документа 136...
Обработка документа 137...
Обработка документа 138...
Обработка документа 139...
Обработка документа 140...
Обработка документа 141...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Дополнительная попытка 29
Дополнительная попытка 30
Обработка документа 142...
Обработка документа 143...
Обработка документа 144...
Обработка документа 145...
Обработка документа 146...
Обработка документа 147...
Обработка документа 148...
Обработка документа 149...
Обработка документа 150...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Обработка документа 151...
Обработка документа 152...
Обработка документа 153...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Обработка документа 154...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Дополнительная попытка 29
Дополнительная попытка 30
Обработка документа 155...
Обработка документа 156...
Обработка документа 157...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Дополнительная попытка 29
Дополнительная попытка 30
Обработка документа 158...
Обработка документа 159...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Обработка документа 160...
Обработка документа 161...
Обработка документа 162...
Обработка документа 163...
Обработка документа 164...
Обработка документа 165...
Обработка документа 166...
Обработка документа 167...
Обработка документа 168...
Обработка документа 169...
Обработка документа 170...
Обработка документа 171...
Обработка документа 172...
Обработка документа 173...
Обработка документа 174...
Обработка документа 175...
Обработка документа 176...
Обработка документа 177...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Дополнительная попытка 29
Дополнительная попытка 30
Обработка документа 178...
Обработка документа 179...
Дополнительная попытка 1
Обработка документа 180...
Обработка документа 181...
Обработка документа 182...
Обработка документа 183...
Обработка документа 184...
Обработка документа 185...
Обработка документа 186...
Обработка документа 187...
Обработка документа 188...
Обработка документа 189...
Обработка документа 190...
Обработка документа 191...
Дополнительная попытка 1
Обработка документа 192...
Обработка документа 193...
Обработка документа 194...
Обработка документа 195...
Обработка документа 196...
Обработка документа 197...
Обработка документа 198...
Обработка документа 199...
Обработка документа 200...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Обработка документа 201...
Обработка документа 202...
Обработка документа 203...
Обработка документа 204...
Обработка документа 205...
Дополнительная попытка 1
Обработка документа 206...
Обработка документа 207...
Обработка документа 208...
Обработка документа 209...
Обработка документа 210...
Обработка документа 211...
Обработка документа 212...
Обработка документа 213...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Обработка документа 214...
Обработка документа 215...
Обработка документа 216...
Обработка документа 217...
Обработка документа 218...
Обработка документа 219...
Обработка документа 220...
Обработка документа 221...
Обработка документа 222...
Обработка документа 223...
Обработка документа 224...
Обработка документа 225...
Обработка документа 226...
Обработка документа 227...
Обработка документа 228...
Обработка документа 229...
Обработка документа 230...
Обработка документа 231...
Обработка документа 232...
Обработка документа 233...
Обработка документа 234...
Обработка документа 235...
Обработка документа 236...
Обработка документа 237...
Обработка документа 238...
Обработка документа 239...
Обработка документа 240...
Дополнительная попытка 1
Обработка документа 241...
Обработка документа 242...
Обработка документа 243...
Обработка документа 244...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Дополнительная попытка 29
Дополнительная попытка 30
Обработка документа 245...
Обработка документа 246...
Обработка документа 247...
Обработка документа 248...
Обработка документа 249...
Обработка документа 250...
Обработка документа 251...
Обработка документа 252...
Обработка документа 253...
Обработка документа 254...
Обработка документа 255...
Обработка документа 256...
Обработка документа 257...
Обработка документа 258...
Обработка документа 259...
Дополнительная попытка 1
Обработка документа 260...
Обработка документа 261...
Обработка документа 262...
Обработка документа 263...
Обработка документа 264...
Обработка документа 265...
Обработка документа 266...
Обработка документа 267...
Обработка документа 268...
Дополнительная попытка 1
Дополнительная попытка 2
Обработка документа 269...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Обработка документа 270...
Обработка документа 271...
Обработка документа 272...
Обработка документа 273...
Обработка документа 274...
Обработка документа 275...
Обработка документа 276...
Обработка документа 277...
Обработка документа 278...
Обработка документа 279...
Обработка документа 280...
Обработка документа 281...
Обработка документа 282...
Обработка документа 283...
Обработка документа 284...
Обработка документа 285...
Обработка документа 286...
Обработка документа 287...
Обработка документа 288...
Обработка документа 289...
Обработка документа 290...
Обработка документа 291...
Обработка документа 292...
Обработка документа 293...
Обработка документа 294...
Обработка документа 295...
Обработка документа 296...
Обработка документа 297...
Обработка документа 298...
Обработка документа 299...
Обработка документа 300...
Обработка документа 301...
Обработка документа 302...
Обработка документа 303...
Обработка документа 304...
Обработка документа 305...
Обработка документа 306...
Обработка документа 307...
Дополнительная попытка 1
Обработка документа 308...
Обработка документа 309...
Обработка документа 310...
Обработка документа 311...
Обработка документа 312...
Обработка документа 313...
Обработка документа 314...
Обработка документа 315...
Обработка документа 316...
Обработка документа 317...
Обработка документа 318...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Дополнительная попытка 11
Дополнительная попытка 12
Дополнительная попытка 13
Дополнительная попытка 14
Дополнительная попытка 15
Дополнительная попытка 16
Дополнительная попытка 17
Дополнительная попытка 18
Дополнительная попытка 19
Дополнительная попытка 20
Дополнительная попытка 21
Дополнительная попытка 22
Дополнительная попытка 23
Дополнительная попытка 24
Дополнительная попытка 25
Дополнительная попытка 26
Дополнительная попытка 27
Дополнительная попытка 28
Дополнительная попытка 29
Дополнительная попытка 30
Обработка документа 319...
Обработка документа 320...
Обработка документа 321...
Обработка документа 322...
Обработка документа 323...
Обработка документа 324...
Обработка документа 325...
Обработка документа 326...
Обработка документа 327...
Обработка документа 328...
Обработка документа 329...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4
Дополнительная попытка 5
Дополнительная попытка 6
Дополнительная попытка 7
Дополнительная попытка 8
Дополнительная попытка 9
Дополнительная попытка 10
Обработка документа 330...
Обработка документа 331...
Обработка документа 332...
Обработка документа 333...
Обработка документа 334...
Обработка документа 335...
Обработка документа 336...
Обработка документа 337...
Дополнительная попытка 1
Дополнительная попытка 2
Дополнительная попытка 3
Дополнительная попытка 4

In [103]:
data_labeled = pd.DataFrame(results)#.drop(['category', 'details'], axis=1)
data_labeled

,Профессиональное среднее спортивное образование,Высшее спортивное образование,Мастер спорта,Кандидат в мастера спорта,Чемпион,Опыт работы,master_id,category,details
0,True,False,False,False,False,4.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
1,True,False,False,False,False,19.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
2,False,True,True,False,True,8.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
3,True,False,False,False,False,2.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
4,True,False,True,False,False,3.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
...,...,...,...,...,...,...,...,...,...
407,True,False,False,True,False,5.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
408,True,False,False,False,False,13.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
409,True,False,True,False,True,9.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
410,True,True,True,False,True,4.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
411,True,False,True,False,False,18.0,https://profi.ru/profile/BazylevPN/,NaN,NaN

In [106]:
data_labeled

,Профессиональное среднее спортивное образование,Высшее спортивное образование,Мастер спорта,Кандидат в мастера спорта,Чемпион,Опыт работы,master_id,category,details
0,True,False,False,False,False,4.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
1,True,False,False,False,False,19.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
2,False,True,True,False,True,8.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
3,True,False,False,False,False,2.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
4,True,False,True,False,False,3.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
...,...,...,...,...,...,...,...,...,...
407,True,False,False,True,False,5.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
408,True,False,False,False,False,13.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
409,True,False,True,False,True,9.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
410,True,True,True,False,True,4.0,https://profi.ru/profile/BazylevPN/,NaN,NaN
411,True,False,True,False,False,18.0,https://profi.ru/profile/BazylevPN/,NaN,NaN

In [ ]:
all_data_final_llm = pd.concat([data_labeled, all_data_final], axis=1)
all_data_final_llm.rename(columns={
        'Профессиональное среднее спортивное образование': 'has_secondary_sport_education',
        'Высшее спортивное образование': 'has_higher_sport_education',
        'Опыт работы': 'work_experience',
        'Мастер спорта': 'sport_master',
        'Кандидат в мастера спорта': 'sport_master_kandidate',
        'Чемпион': 'is_champion'}, inplace=True)

In [108]:
all_data_final_llm

,has_secondary_sport_education,has_higher_sport_education,sport_master,sport_master_kandidate,is_champion,work_experience,master_id,category,details,master_id,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
0,True,False,False,False,False,4.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AbelkhairovaSV/,...,None,50.493489,29,10,,На сервисе с декабря 2023 г. (2 года)\nФотогра...,"РУС ГЦОЛИФК, реабилитация, ЛФКс 2023 г. (3 года)",,Если ты всегда мечтал научиться играть в больш...,; На сервисе с декабря 2023 г. (2 года)\nФотог...
1,True,False,False,False,False,19.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AbramovMB/,...,None,50.433670,2,0,,На сервисе с марта 2026 г,,,,; На сервисе с марта 2026 г; ; ;
2,False,True,True,False,True,8.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AbyasovaAN/,...,None,50.350443,31,0,,На сервисе с октября 2023 г. (2 года),,,"Стаж: 6 лет\nМастер спорта, многократный побед...",; На сервисе с октября 2023 г. (2 года); ; ; С...
3,True,False,False,False,False,2.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AfanasyevBA4/,...,None,50.330329,15,8,,"Компания СУЭК-КУЗБАСС МФСЦ""ГОРНЯК""2023–2025 гг...",АНО ДПО НАДПО программа дополнительного профес...,"Обучаю с ""0"". За полгода работы,ученики участв...",Тренер по большому теннису. Провожу индивидуал...,"; Компания СУЭК-КУЗБАСС МФСЦ""ГОРНЯК""2023–2025 ..."
4,True,False,True,False,False,3.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/AgureyevaKM2/,...,None,50.512069,8,0,Мастер спорта по теннису2022 г.\nДокументы и с...,На сервисе с сентября 2025 г,,,Здравствуйте! Меня зовут Ксения! Я мастер спор...,Мастер спорта по теннису2022 г.\nДокументы и с...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,True,False,False,True,False,5.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/ZhirkovaVA10/,...,None,50.094330,2,2,,На сервисе с марта 2026 г\nФотографии2,,,"Всем привет! Меня зовут Вероника, я тренер по ...",; На сервисе с марта 2026 г\nФотографии2; ; ; ...
408,True,False,False,False,False,13.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/ZhuchkovaVS3/,...,None,50.019230,9,0,,На сервисе с августа 2025 г,,,Тренер по теннису & Спарринг-партнер | Все уро...,; На сервисе с августа 2025 г; ; ; Тренер по т...
409,True,False,True,False,True,9.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/ZhukovMA78/,...,None,50.461117,1,3,,На сервисе с апреля 2026 г\nФотографии3,,,Профессиональный теннисист (ATP 449).\nМастер ...,; На сервисе с апреля 2026 г\nФотографии3; ; ;...
410,True,True,True,False,True,4.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/ZykovaDS2/,...,None,50.479362,33,2,Мастер спорта по теннису2022 г.\nФотографии2\n...,На сервисе с августа 2023 г. (2 года),,,"Здравствуйте, меня зовут Дарья!\nС 3х лет проф...",Мастер спорта по теннису2022 г.\nФотографии2\n...
411,True,False,True,False,False,18.0,https://profi.ru/profile/BazylevPN/,NaN,NaN,https://profi.ru/profile/user5599460/,...,None,50.438705,49,5,"Министерство спорта Российской Федерации, маст...",На сервисе с апреля 2022 г. (4 года),,,Мастер спорта РФ\nНа корте с 2005 года\nСтаж т...,"Министерство спорта Российской Федерации, маст..."

### Делаем все ручками, где наш слон не справился

In [117]:
bad_data_mask = all_data_final_llm['has_secondary_sport_education'].isna()
bad_data = all_data_final_llm[bad_data_mask]

In [121]:
bad_data

,has_secondary_sport_education,has_higher_sport_education,sport_master,sport_master_kandidate,is_champion,work_experience,master_id,category,details,master_id,...,contract,cur_score,profi_ru_start,photos_count,achivements,experience,education,additional_info,about_coach,coach5_cols
91,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting value: line 1 column 1 (char 0),https://profi.ru/profile/GalustyanAR2/,...,None,50.500000,118,14,,Опыт тренерской работыс 2002 г. (24 года)\nНа ...,Российский государственный университет физичес...,PTR Instructor\nФотографии14\nВсе альбомы и фо...,Участник российских соревнований: первенство М...,; Опыт тренерской работыс 2002 г. (24 года)\nН...
95,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting property name enclosed in double quo...,https://profi.ru/profile/GerlakhDO/,...,None,50.410983,23,2,,Тренер по теннисус 2017 г. (9 лет)\nНа сервисе...,,,Предлагаю свои услуги в качестве тренера / спа...,; Тренер по теннисус 2017 г. (9 лет)\nНа серви...
140,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting value: line 1 column 1 (char 0),https://profi.ru/profile/KazakovSA18/,...,None,50.573557,65,3,5 место на Первенстве России среди ветеранов (...,ФОК «Южное Бутово»2003–2021 гг.\nФОК Южное Бут...,Российский государственный университет физичес...,,Тренерский стаж с 2003 г. Лучшие ученики: Шадч...,5 место на Первенстве России среди ветеранов (...
153,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting property name enclosed in double quo...,https://profi.ru/profile/KlichnikovAY/,...,None,50.550369,12,0,,На сервисе с мая 2025 г,,,"Профессиональный игрок, КМС, победитель и приз...",; На сервисе с мая 2025 г; ; ; Профессиональны...
156,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting property name enclosed in double quo...,https://profi.ru/profile/KolobaevNE/,...,None,50.492534,57,4,,На сервисе с августа 2021 г. (4 года)\nФотогра...,,,— Играю в теннис на протяжении 20 лет\n— Побед...,; На сервисе с августа 2021 г. (4 года)\nФотог...
176,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting property name enclosed in double quo...,https://profi.ru/profile/LapinAV24/,...,None,50.511435,58,5,,На сервисе с июля 2021 г. (4 года)\nФотографии5,,,"Тренерской деятельностью занимаюсь 7 лет, как ...",; На сервисе с июля 2021 г. (4 года)\nФотограф...
243,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting property name enclosed in double quo...,https://profi.ru/profile/NurmatovBR/,...,None,50.610950,66,0,"Турнир Pickleball Russia, 1 место2025 г.\nДоку...",Школа тенниса Tenniseasyс 2023 г. (3 года)\nНа...,"Федерация падела России, семинар для тренеров ...",,Опыт работы тренером по теннису уже более 3 ле...,"Турнир Pickleball Russia, 1 место2025 г.\nДоку..."
317,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting property name enclosed in double quo...,https://profi.ru/profile/SeredaAE2/,...,None,50.450012,43,2,,На сервисе с октября 2022 г. (3 года)\nФотогра...,,,Занимаюсь теннисом 15 лет. Являюсь действующим...,; На сервисе с октября 2022 г. (3 года)\nФотог...
336,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting property name enclosed in double quo...,https://profi.ru/profile/SmirnovTZ/,...,None,50.518710,4,0,,На сервисе с января 2026 г,,,"Здравствуйте\nМеня зовут Тимофей, мне 20 лет, ...",; На сервисе с января 2026 г; ; ; Здравствуйте...
377,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting property name enclosed in double quo...,https://profi.ru/profile/VanyukovaSA3/,...,None,50.451209,48,25,,На сервисе с мая 2022 г. (3 года)\nФотографии2...,,,"Профессиональная теннисистка, чемпионка Ленинг...",; На сервисе с мая 2022 г. (3 года)\nФотографи...
381,NaN,NaN,NaN,NaN,NaN,NaN,https://profi.ru/profile/VakulichevVL/,Ошибка,Expecting value: line 1 column 1 (char 0),https://profi.ru/profile/VimbaPA/,...,None,50.505322,20,8,"Открытый чемпионат RER SUD, третье место2019 г...",На сервисе с сентября 2024 г. (1 год),,,Являюсь многократным победителем и призером Ро...,"Открытый чемпионат RER SUD, третье место2019 г..."

In [139]:
## 24 года Опыта, высшее образование, не победитель, нет спортивных званий
bad_data['coach5_cols'][91]

'; Опыт тренерской работыс 2002 г. (24 года)\nНа сервисе с июля 2016 г. (9 лет); Российский государственный университет физической культуры, спорта, молодежи и туризма (ГЦОЛИФК), курс повышения квалификации, дополнительная профессиональная программа «Актуальные проблемы подготовки теннисистов», г. Москва2017 г.; PTR Instructor\nФотографии14\nВсе альбомы и фотографии\nВидео17; Участник российских соревнований: первенство Москвы, юношеские турниры, международные командные турниры. Участник турниров ITF Futures (США).\nАвтор кроссвордов для журнала Теннис +.\nФиналист конкурса знатоков тенниса НТВ (Дмитриева А.В.).'

In [140]:
all_data_final_llm.iloc[91, 0] = 0
all_data_final_llm.iloc[91, 1] = 1
all_data_final_llm.iloc[91, 2] = 0
all_data_final_llm.iloc[91, 3] = 0
all_data_final_llm.iloc[91, 4] = 0
all_data_final_llm.iloc[91, 5] = 24

In [141]:
## 9 лет Опыта, высшее образование, победитель, кмс
bad_data['coach5_cols'][95]

'; Тренер по теннисус 2017 г. (9 лет)\nНа сервисе с июня 2024 г. (1 год)\nФотографии2; ; ; Предлагаю свои услуги в качестве тренера / спарринг партнера по большому теннису для детей и взрослых.\nНаучу играть с нуля и поставлю красивую технику.\nЯ — победитель и призер российских и международных турниров. КМС. Играла за команду в университете в США. Опыт работы в качестве тренера 7 лет.\nМогу проводить тренировки на английском языке.'

In [142]:
all_data_final_llm.iloc[95, 0] = 0
all_data_final_llm.iloc[95, 1] = 1
all_data_final_llm.iloc[95, 2] = 1
all_data_final_llm.iloc[95, 3] = 0
all_data_final_llm.iloc[95, 4] = 1
all_data_final_llm.iloc[95, 5] = 9

In [ ]:
## 23 года Опыта, высшее образование, победитель, нет званий
bad_data['coach5_cols'][140]

'5 место на Первенстве России среди ветеранов (классификация РТТ)2008 г.\nПобедитель первенства России среди ветеранов в парном разряде2021 г.\nФотографии3; ФОК «Южное Бутово»2003–2021 гг.\nФОК Южное Бутово, тренерс 2003 г. (23 года)\nНа сервисе с декабря 2020 г. (5 лет); Российский государственный университет физической культуры, спорта, молодёжи и туризма (ГЦОЛИФК), курс повышения квалификации по дополнительной профессиональной программе «Актуальные проблемы подготовки теннисистов»2018 г.; ; Тренерский стаж с 2003 г. Лучшие ученики: Шадчнева Даша 2006 г. р.\nна сегодняшний день первая ракетка России по своему возрасту,\nчлен сборной России по теннису, в 2022 году стала победителем Первенства России до 19 лет и получила звание «МАСТЕР СПОРТА РОССИИ в пятнадцать лет, победительница многих российских и европейских турниров, на сегодня третья в Европе (см. классификацию РТТ и ТЕ),\nМальцев Илья 2007 г. р. на сегодняшний день входит в тройку в России по своему возрасту, член сборной России, победитель многих Российских и Европейских турниров (см. классификации РТТ и ТЕ)'

In [143]:
all_data_final_llm.iloc[140, 0] = 0
all_data_final_llm.iloc[140, 1] = 1
all_data_final_llm.iloc[140, 2] = 0
all_data_final_llm.iloc[140, 3] = 0
all_data_final_llm.iloc[140, 4] = 1
all_data_final_llm.iloc[140, 5] = 23

In [144]:
## 1 год Опыта, победитель, кмс, без образования
bad_data['coach5_cols'][153]

'; На сервисе с мая 2025 г; ; ; Профессиональный игрок, КМС, победитель и призер многочисленных турниров РТТ и ITF'

In [145]:
all_data_final_llm.iloc[153, 0] = 0
all_data_final_llm.iloc[153, 1] = 0
all_data_final_llm.iloc[153, 2] = 0
all_data_final_llm.iloc[153, 3] = 1
all_data_final_llm.iloc[153, 4] = 1
all_data_final_llm.iloc[153, 5] = 1

In [146]:
## 7 лет Опыта, победитель, без званий, без образования
bad_data['coach5_cols'][156]

'; На сервисе с августа 2021 г. (4 года)\nФотографии4; ; ; — Играю в теннис на протяжении 20 лет\n— Победитель и призер турниров РТТ, TE, ITF\n— Входил в состав сборной России и сборной Израиля\n— Проходил подготовку в академиях: Испании, Словакии, Австрии и Израиля\n— Работаю тренером более 7 лет.\nПривет всем любителям большого тенниса, меня зовут Николай.\nПровожу индивидуальные и групповые тренировки для детей и взрослых любого уровня подготовки.\n— обучения с нуля детей и взрослых\n— подготовка профессиональных спортсменов\n— обучение современной правильной техники, исключающей травматизм\n— помогу повысить качество игры\n— подготовлю к соревнованиям'

In [147]:
all_data_final_llm.iloc[156, 0] = 0
all_data_final_llm.iloc[156, 1] = 0
all_data_final_llm.iloc[156, 2] = 0
all_data_final_llm.iloc[156, 3] = 0
all_data_final_llm.iloc[156, 4] = 1
all_data_final_llm.iloc[156, 5] = 7

In [148]:
## 7 лет Опыта, не победитель, без званий, без образования
bad_data['coach5_cols'][176]

'; На сервисе с июля 2021 г. (4 года)\nФотографии5; ; ; Тренерской деятельностью занимаюсь 7 лет, как индивидуальных так и групповых занятий\nМне 25 лет, родом из Волгограда, большую часть карьеры выступал за этот город, также входил в топ-10 теннисистов Классификации РТТ'

In [149]:
all_data_final_llm.iloc[176, 0] = 0
all_data_final_llm.iloc[176, 1] = 0
all_data_final_llm.iloc[176, 2] = 0
all_data_final_llm.iloc[176, 3] = 0
all_data_final_llm.iloc[176, 4] = 0
all_data_final_llm.iloc[176, 5] = 7

In [150]:
## 3 года Опыта, победитель, кмс, высшее образование
bad_data['coach5_cols'][243]

'Турнир Pickleball Russia, 1 место2025 г.\nДокументы и сертификаты2; Школа тенниса Tenniseasyс 2023 г. (3 года)\nНа сервисе с ноября 2020 г. (5 лет); Федерация падела России, семинар для тренеров по паделу2025 г.; ; Опыт работы тренером по теннису уже более 3 лет, а играю в теннис уже более 15 лет, победитель и призер турниров первой категории, разряд КМС.\nВ первую очередь пытаюсь сделать тренировку приятной и комфортной, могу помочь достичь любые ваши спортивные цели и построить план развития в теннисе, могу быть тренером/спарингом. Буду рад помочь вам заниматься вашим любимым спортом)\nТакже являюсь тренером по падел и пиклболу !!!👈\nПо пиклболу выйграл чемпионат Москвы 24.05.2025 и 20.07.2025'

In [151]:
all_data_final_llm.iloc[243, 0] = 0
all_data_final_llm.iloc[243, 1] = 1
all_data_final_llm.iloc[243, 2] = 0
all_data_final_llm.iloc[243, 3] = 1
all_data_final_llm.iloc[243, 4] = 1
all_data_final_llm.iloc[243, 5] = 3

In [152]:
## 3 года Опыта, победитель, без звания, без образования
bad_data['coach5_cols'][317]

'; На сервисе с октября 2022 г. (3 года)\nФотографии2; ; ; Занимаюсь теннисом 15 лет. Являюсь действующим профессиональным игроком. Участвую в международных соревнования. Призер Первенства России в парном разряде, а так же победительница турниров РТТ/ITF. Могу обучить с нуля как ребенка так и взрослого. Так же могу быть спаррингом для профессионала. Проведу полноценную тренировку по ОФП'

In [153]:
all_data_final_llm.iloc[317, 0] = 0
all_data_final_llm.iloc[317, 1] = 0
all_data_final_llm.iloc[317, 2] = 0
all_data_final_llm.iloc[317, 3] = 0
all_data_final_llm.iloc[317, 4] = 1
all_data_final_llm.iloc[317, 5] = 3

In [154]:
## о года Опыта, победитель, без звания, без образования
bad_data['coach5_cols'][336]

'; На сервисе с января 2026 г; ; ; Здравствуйте\nМеня зовут Тимофей, мне 20 лет, являюсь действующим игроком, тренером и спарринг партнером по большому теннису.\nТеннис — динамичный и востребованный вид спорта, который формирует не только тело, но и мышление. Я в теннисе профессионально 12 лет. Неоднократный победитель и призёр турниров РТТ, также участник турниров ITF. Подберу правильный подход к тренировкам исходя от ваших целей.\nВ мои услуги входит:\n•Постановка техники игры\n•Поддержка и развитие физической формы\n•Спарринг\nПодберем удобное время и локацию для ваших тренировок.'

In [155]:
all_data_final_llm.iloc[336, 0] = 0
all_data_final_llm.iloc[336, 1] = 0
all_data_final_llm.iloc[336, 2] = 0
all_data_final_llm.iloc[336, 3] = 0
all_data_final_llm.iloc[336, 4] = 1
all_data_final_llm.iloc[336, 5] = 0

In [156]:
## 4 года Опыта, победитель, без звания, без образования
bad_data['coach5_cols'][377]

'; На сервисе с мая 2022 г. (3 года)\nФотографии25\nВсе альбомы и фотографии; ; ; Профессиональная теннисистка, чемпионка Ленинградской области, сертифицированный тренер/спаринг по большому теннису, играю турниры РТТ, играю в теннис больше 14 лет, тренирую детей и взрослых, играю насчет с детьми'

In [157]:
all_data_final_llm.iloc[377, 0] = 0
all_data_final_llm.iloc[377, 1] = 0
all_data_final_llm.iloc[377, 2] = 0
all_data_final_llm.iloc[377, 3] = 0
all_data_final_llm.iloc[377, 4] = 1
all_data_final_llm.iloc[377, 5] = 4

In [158]:
## 2 года Опыта, победитель, без звания, без образования
bad_data['coach5_cols'][381]

'Открытый чемпионат RER SUD, третье место2019 г.\nОсенний кубок г. Донской, 1 место в турнире по теннису2023 г.\nМинистерство физической культуры и спорта Московской области, 1 место в одиночном разряде на турнире «Кубок Московской области»2024 г.\nМинистерство физической культуры и спорта Московской области, участник команды, занявшей 1 место в Командном Первенстве Московской области2024 г.\nПобедитель Всероссийских соревнований «Кубок Анастасии Павлюченковой на призы Tennis Life»2024 г.\nОсенний кубок президента международной академии тенниса Шамиля Тарпищева, победительница в одиночном разряде среди юниорок до 19 лет2024 г.\nЛФТ, 1 место в «Первенство г.о Люберцы на призы Фирмы "Кухонный двор"»2025 г.\nСпортивный клуб «Балашиха», победитель Чемпионата ЦФО 20252025 г.\nЦентр спортивной подготовки, всероссийские сорвенования «Кубок Рязанского кремля», 1 место2025 г.\nФотографии8\nВсе альбомы и фотографии\nДокументы и сертификаты7; На сервисе с сентября 2024 г. (1 год); ; ; Являюсь многократным победителем и призером Российских и Европейских турниров в одиночном и парном разрядах первенств Московской, Нижегородской, Ленинградской областей, также в г. Москва, Дмитров, Сергиев-Посад, Истра, Красногорск, Донской, Севастополь в разных возрастных категориях.\nВ 2019 году поднялась в рейтинге РТТ на 99 позиций и на 1 февраля 2020 г. занимала 1-ю позицию среди девушек до 13 лет в классификации РТТ. На 01.09.2024 занимаю 4-ю позицию среди девушек до 17 лет.\nВходила в состав сборной команды России по теннису в 2020—2021 год (до 13 лет).\nВ феврале 2020 г. выиграла зональный этап Зимнего Кубка Европы в г. Таллинне (Эстония) в составе сборной команды России и Финалист Кубка Европы в г. Сандерленд (Англия).\nПобедитель престижного международного турнира ТЕ «Pirogovskiy Winter Cup 2020» (г. Москва) среди девушек до 13 лет (январь 2020 г.).\nФиналист Т Е турниров одиночном и парном разряде г. Руссе Болгария,\nг. Бузаэ, Румыния\nПобедитель Всероссийских соревнований «Олимпийские надежды России» до 15 лет.\nПобедитель Первенства и Кубка Москвы\nв одиночном и парном разряде до 17 лет.\nПобедитель Зимнего Кубка международной академии тенниса Шамиля Тарпищева до 19 лет.'

In [159]:
all_data_final_llm.iloc[381, 0] = 0
all_data_final_llm.iloc[381, 1] = 0
all_data_final_llm.iloc[381, 2] = 0
all_data_final_llm.iloc[381, 3] = 0
all_data_final_llm.iloc[381, 4] = 1
all_data_final_llm.iloc[381, 5] = 2

In [160]:
all_data_final_llm.isna().sum()

has_secondary_sport_education      0
has_higher_sport_education         0
sport_master                       0
sport_master_kandidate             0
is_champion                        0
work_experience                   26
master_id                          0
category                         401
details                          401
master_id                          0
index                              0
docs_verified                      0
gender                             9
guarantee                          0
rating                             0
reviews_count                      0
assembledInfoListing               0
is_highly_praised                  0
is_certified                       0
price_socket                      93
discount                         342
insurance                        411
contract                         412
cur_score                          1
profi_ru_start                     0
photos_count                       0
achivements                        0
experience                         0
education                          0
additional_info                    0
about_coach                        0
coach5_cols                        0
dtype: int64

In [161]:
all_data_final_llm.to_csv('all_data_llm_tennis_moskow.csv', index=False)